<?php 
	$module = $this->getRequest()->getModule();
?>
<script type="text/javascript">
	$(function() {
		$('.lg').click(function() {
			var id = $(this).attr('rel');
			$(this).addClass('selected').parent().siblings().find('a').removeClass('selected');
			$('#name_' + id).show().siblings('input').hide();
			$('#name_' + id).next('img').show().siblings('img').hide();
			
			var tid = '#txt_' + id;
			$(tid).show().siblings('div').hide();
			
			return false;
		});
	});
</script>
<form name="admin_form" id="admin_form" method="post" action="">
<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/<?php echo $module;?>/images/page_white_link.png">
		<?php echo $this->translate('Pages');?> <?php echo (!empty($this->parent_name[JO_Registry::get('default_config_language_id')]) ? ' › ' . $this->parent_name[JO_Registry::get('default_config_language_id')] : '');?>
	</h3>
	
	<span id="fader" class="fleft mleft30" style="display:none;">
		<span class="msgError"><span><?php echo $this->translate('Error!');?></span><i class="error_text"></i></span>
	</span>
	
	<div class="fright mtop3">
		<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
		<a class="button" href="<?php echo $module;?>/pages/<?php echo ($this->sub_of ? '?sub_of=' . $this->sub_of : '');?>"><?php echo $this->translate('Cancel');?></a>
	</div>
	<div class="clear"></div>
</div>

<div class="clear"></div>
	<div class="tabs mtop3">
		<ul>
			<li><a href="#tab_general"><?php echo $this->translate('Information');?></a></li>
			<li><a href="#tab_seo"><?php echo $this->translate('SEO');?></a></li> 
		</ul> 
		<div class="clear"></div>
	</div>
	
		<div id="tab_general">
			<div class="tabs mtop10">
				<ul>
					<?php foreach($this->languages AS $language) { ?>
					<li>
						<a href="#" rel="<?php echo $language['language_id'];?>" class="<?php echo $this->def_lang == $language['code'] ? 'selected ' : '';?>lg">
							<img src="cms/images/flags/<?php echo $language['image'];?>" />
							<?php echo $language['name'];?>
						</a>
					</li> 
					<?php } ?>
				</ul>
				<div class="clear"></div>
			</div>
		<table cellspacing="0" cellpadding="0" class="formtable">
			<tbody>
				<tr>
					<td width="150"><?php echo $this->translate('Name');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
					<td>
						<?php foreach($this->languages AS $language) { ?>
						<input type="text" id="name_<?php echo $language['language_id'];?>" name="name[<?php echo $language['language_id']; ?>]" title="<?php echo $this->translate('Please enter a name');?>" size="40" value="<?php echo $this->name[$language['language_id']]; ?>"  class="inputbox"<?php echo ($language['code'] != $this->def_lang) ? ' style="display:none; "' : '';?>/>
						<img src="cms/images/flags/<?php echo $language['image'];?>"<?php echo ($language['code'] != $this->def_lang) ? ' style="display:none; "' : '';?>/>
						<?php } ?>
					</td>
				</tr>
				<tr>
					<td><?php echo $this->translate('Description');?>: </td>
	        		<td>
	        			<?php foreach($this->languages AS $language) { ?>
	        			<div id="txt_<?php echo $language['language_id'];?>"<?php echo ($language['code'] != $this->def_lang) ? ' style="display:none;"' : '';?>>
							<textarea rows="4" cols="53"  name="text[<?php echo $language['language_id']; ?>]" class="valid ckeditor_replace"><?php echo $this->text[$language['language_id']]; ?></textarea>
							<img src="cms/images/flags/<?php echo $language['image'];?>"/>
						</div>
						<?php } ?>
					</td>
				</tr>
				<tr>
					<td><?php echo $this->translate('Visible');?>: </td>
					<td>
						<select class="inputbox"  name="visible">
							<?php if($this->visible == 'true') { ?>
							<option selected="selected" value="true"><?php echo $this->translate('Yes');?></option>
							<option value="false"><?php echo $this->translate('No');?></option>
							<?php } else { ?>
							<option value="true"><?php echo $this->translate('Yes');?></option>
							<option selected="selected" value="false"><?php echo $this->translate('No');?></option>
							<?php } ?>
						</select>
	        		</td>
				</tr>
				<tr>
					<td><?php echo $this->translate('Show in the main menu');?>: </td>
					<td>
						<select class="inputbox"  name="menu">
							<?php if($this->menu == 'true') { ?>
							<option selected="selected" value="true"><?php echo $this->translate('Yes');?></option>
							<option value="false"><?php echo $this->translate('No');?></option>
							<?php } else { ?>
							<option value="true"><?php echo $this->translate('Yes');?></option>
							<option selected="selected" value="false"><?php echo $this->translate('No');?></option>
							<?php } ?>
						</select>
	        		</td>
				</tr>
				<tr>
					<td><?php echo $this->translate('Show in the footer');?>: </td>
					<td>
						<select class="inputbox"  name="footer">
							<?php if($this->footer == 'true') { ?>
							<option selected="selected" value="true"><?php echo $this->translate('Yes');?></option>
							<option value="false"><?php echo $this->translate('No');?></option>
							<?php } else { ?>
							<option value="true"><?php echo $this->translate('Yes');?></option>
							<option selected="selected" value="false"><?php echo $this->translate('No');?></option>
							<?php } ?>
						</select>
	        		</td>
				</tr>
				<tr>
					<td width="150"><?php echo $this->translate('URL');?>: </td>
					<td>
						<input type="text" size="40" value="<?php echo $this->url;?>" class="inputbox"  name="url" />
	        		</td>
				</tr>
			</tbody>
		</table>
	</div>
	
	<div id="tab_seo">
		<table cellspacing="0" cellpadding="0" class="formtable">
			<tbody>
				<tr>
					<td width="150"><?php echo $this->translate('SEO Key');?>:</td>
					<td>
						<input type="text" size="40" value="<?php echo $this->key;?>" class="inputbox"  name="key" />
	        		</td>
				</tr>
				<tr>
					<td width="150"><?php echo $this->translate('Meta title');?>:</td>
					<td>
						<input type="text" size="40" value="<?php echo $this->meta_title;?>" class="inputbox"  name="meta_title" />
	        		</td>
				</tr>
				<tr>
					<td width="150"><?php echo $this->translate('Meta keywords');?>:</td>
					<td>
						<input type="text" size="40" value="<?php echo $this->meta_keywords;?>" class="inputbox"  name="meta_keywords" />
	        		</td>
				</tr>
				<tr>
					<td width="150"><?php echo $this->translate('Meta description');?>:</td>
					<td>
						<input type="text" size="40" value="<?php echo $this->meta_description;?>" class="inputbox"  name="meta_description" />
	        		</td>
				</tr>
			</tbody>
		</table>
	</div>
		
		<div class="info_line bottom">
			<div class="fright mtop3">
				<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
				<a class="button" href="<?php echo $module;?>/pages/<?php echo ($this->sub_of ? '?sub_of=' . $this->sub_of : '');?>"><?php echo $this->translate('Cancel');?></a>
			</div>
			<div class="clear"></div>
		</div>
		
		<div class="clear"></div>
		
	</form>
	
<script type="text/javascript"> 
	$(document).ready(function(){
		$(".tabs ul").idTabs(); 
	});
</script>