<?php 
	$module = $this->getRequest()->getModule();
?>

<form name="admin_form" id="admin_form" method="post" action="" enctype="multipart/form-data">

	<div class="info_line top">
		<h3 class="fleft title">
			<img alt="" src="cms/<?php echo $module;?>/images/contacts.png">
			<?php echo $this->translate('Notification templates Management');?>
		</h3>
		
		<span id="fader" class="fleft mleft30" style="display:none;">
			<span class="msgError"><span><?php echo $this->translate('Error!');?></span><i class="error_text"></i></span>
		</span>
		
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/notificationtemplates/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>

	<div class="clear"></div>
	
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Title');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" title="<?php echo $this->translate('Please enter Title');?>" size="50" value="<?php echo $this->title;?>" class="inputbox required"  name="title" />
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Template');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<textarea rows="4" cols="53" name="template" class="ckeditor_replace"><?php echo $this->template1;?></textarea>
        		</td>
			</tr>
			<?php if($this->getRequest()->getAction() == '') { ?>
			<tr>
				<td width="150"><?php echo $this->translate('Information');?>: </td>
				<td>
					<textarea rows="4" cols="53" name="info"><?php echo $this->info;?></textarea>
        		</td>
			</tr>
			<?php } else { ?>
			<tr>
				<td colspan="2">
					<div class="msgAlert">
						<span style="float: left;"><?php echo $this->translate('Information!');?></span>
						<div style="float: left;"><?php echo nl2br($this->info);?></div>
						<div class="clear"></div>
					</div>
        		</td>
			</tr>
			<?php } ?>
		</tbody>
	</table>
		
	<div class="info_line bottom">
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/notificationtemplates/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
		
</form>