<?php 
	$module = $this->getRequest()->getModule();
?>

<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/<?php echo $module;?>/images/contacts.png">
		<?php echo $this->translate('Notification templates Management');?>
	</h3>
	
	<?php if($this->successfu_edite) { ?>
	<span id="fader" class="fleft mleft30"><span class="msgOk"><span><?php echo $this->translate('Successfully!');?></span><?php echo $this->translate('Information was successfully changed!');?></span></span>
	<script type="text/javascript"> 
	// <![CDATA[
	$(document).ready(function() {       
		setTimeout(function() {
			$("#fader").customFadeOut("slow" ,    
			function() {       
				$("#fader").remove();  
			});
		},
		4000);
	});
	// ]]>
	</script>
	<?php } ?>
	
	<div class="clear"></div>
</div>
<p class="info">
	<?php echo $this->translate('Notification templates Management');?><br>
</p>
<table cellspacing="0" cellpadding="0" class="display">
	<thead>
		<tr class="nodrop nodrag">
			<th class="left"><?php echo $this->translate('Key');?></th>
			<th class="left"><?php echo $this->translate('Title');?></th>
			<th width="50"><?php echo $this->translate('Edit');?></th>
		</tr>
	</thead>
	<tbody>
	<?php if($this->percents) { ?>
	<?php foreach($this->percents AS $percent) { ?>
		<tr>
			<td><?php echo $percent['key'];?></td>
			<td><?php echo $percent['title'];?></td>
			<td align="center"><a href="<?php echo $module;?>/notificationtemplates/edit/?id=<?php echo $percent['key'];?>"><img title="<?php echo $this->translate('Edit');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/edit.png"></a></td>
		</tr>
	<?php } ?>
	<?php } else { ?>
		<tr class="nodrop nodrag">
			<td colspan="3">
				<div class="msgAlert"><span><?php echo $this->translate('Attention!');?></span><?php echo $this->translate('No records found ...');?></div>
			</td>
		</tr>
	<?php } ?>
	</tbody>
</table>
<p class="info">
	<?php echo $this->translate('Cron job - daily summary');?> /<?php echo $this->translate('after'); ?> 22:00/<b style="margin-left:50px;">curl <?php echo $this->cron_link; ?></b><br>
</p>
