<?php 
	$module = $this->getRequest()->getModule();
?>

<form name="admin_form" id="admin_form" method="post" action="">

	<div class="info_line top">
		<h3 class="fleft title">
			<img alt="" src="cms/<?php echo $module;?>/images/cash.png">
			<?php echo $this->translate('Payments');?> › <?php echo $this->translate('Paypal');?>
		</h3>
		
		<span id="fader" class="fleft mleft30" style="display:none;">
			<span class="msgError"><span><?php echo $this->translate('Error');?>!</span><i class="error_text"></i></span>
		</span>
		
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/payments/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>

	<div class="clear"></div>
	
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Status');?>: </td>
				<td>
					<select name="paypal[paypal_status]">
						<?php if($this->paypal_status) { ?>
						<option selected="selected" value="1"><?php echo $this->translate('Enabled');?></option>
						<option value="0"><?php echo $this->translate('Disabled');?></option>
						<?php } else { ?>
						<option value="1"><?php echo $this->translate('Enabled');?></option>
						<option selected="selected" value="0"><?php echo $this->translate('Disabled');?></option>
						<?php } ?>
					</select>
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Sandbox Mode');?>: </td>
				<td>
					<select name="paypal[paypal_sandbox_mode]">
						<?php if($this->paypal_sandbox_mode) { ?>
						<option selected="selected" value="1"><?php echo $this->translate('Yes');?></option>
						<option value="0"><?php echo $this->translate('No');?></option>
						<?php } else { ?>
						<option value="1"><?php echo $this->translate('Yes');?></option>
						<option selected="selected" value="0"><?php echo $this->translate('No');?></option>
						<?php } ?>
					</select>
        		</td>
			</tr>
			
			
			<tr>
				<td><?php echo $this->translate('E-mail');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" title="<?php echo $this->translate('Please enter E-mail');?>" size="60" value="<?php echo $this->paypal_email;?>" class="inputbox required"  name="paypal[paypal_email]" />
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Sort');?>:</td>
				<td>
					<input type="text" size="60" value="<?php echo $this->paypal_sort_order;?>" class="inputbox"  name="paypal[paypal_sort_order]" />
        		</td>
			</tr>
			
			<tr>
				<td><?php echo $this->translate('Logo');?>:</td>
				<td>
					<input type="hidden" name="paypal[paypal_logo]" value="<?php echo $this->paypal_logo; ?>" id="site_logo" />
					<img id="preview_logo" src="<?php echo $this->preview_logo;?>" />
					<br />
					<a style="cursor: pointer;" onclick="image_upload('site_logo', 'preview_logo');"><?php echo $this->translate('Browse Files'); ?></a>
					&nbsp;&nbsp;|&nbsp;&nbsp;
					<a style="cursor: pointer;" onclick="$('#preview_logo').attr('src', '<?php echo $this->preview; ?>'); $('#site_logo').attr('value', '');"><?php echo $this->translate('Clear Image'); ?></a>
				</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('PDT Token');?>:</td>
				<td>
					<input type="text" size="60" value="<?php echo $this->paypal_pdt_token;?>" class="inputbox"  name="paypal[paypal_pdt_token]" />
					<br />
					<span class="help">
						<?php echo $this->translate('Payment Data Transfer Token is used for additional security and reliability. Find out how to enable PDT')?>
						<a href="https://cms.paypal.com/us/cgi-bin/?&cmd=_render-content&content_ID=developer/howto_html_paymentdatatransfer" target="_blank"><?php echo $this->translate('here');?></a>
					</span>
        		</td>
			</tr>
			
		</tbody>
	</table>
		
	<div class="info_line bottom">
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/payments/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
		
</form>

<script type="text/javascript"><!--
function image_upload(field, preview) {
	$('#dialog').remove();
	
	$('#content').prepend('<div id="dialog" style="padding: 3px 0px 0px 0px;"><iframe src="<?php echo $module;?>/filemanager?field=' + encodeURIComponent(field) + '" style="padding:0; margin: 0; display: block; width: 100%; height: 100%;" frameborder="no" scrolling="auto"></iframe></div>');
	
	$('#dialog').dialog({
		title: '<?php echo $this->translate('File Manager');?>',
		close: function (event, ui) {
			if ($('#' + field).attr('value')) {
				$.ajax({
					url: '<?php echo $module;?>/filemanager/image',
					type: 'POST',
					data: 'image=' + encodeURIComponent($('#' + field).val()),
					dataType: 'text',
					success: function(data) {
						$('#' + preview).attr('src',data);
					}
				});
			}
		},	
		bgiframe: false,
		width: 800,
		height: 400,
		resizable: false,
		modal: false
	});
};
//--></script>