<div id="main" class="withhead">
	<h3 class="title-5"><?php echo $this->formtitle?></h3>
	<?php if(isset($this->msg_success)) { ?>
	<p id="msg" class="msg<?php echo isset($this->msg_success) ? ' box-success' : ''; ?>"><?php echo isset($this->msg_success) ? $this->msg_success : ''; ?></p>
	<?php } ?>
	<form action="" method="post" style="padding-top: 15px;" class="form">
		<input type="hidden" id="f5" name="user" value="<?php echo $this->user['username']; ?>" />
		<?php if(isset($this->error['epassword'])) { ?>
		<p class="small errormessage"><?php echo $this->error['epassword']; ?></p>
		<?php } ?>
		<p class="input">
			<label for="f1" class="label"><?php echo $this->translate('Current Password'); ?> *<br class="hide" /></label>
			<input type="password" name="password" id="f1" value="" <?php echo isset($this->error['epassword']) ? 'class="errorborder" ' : '' ;?>/>
		</p>
		<?php if(isset($this->error['enew_password'])) { ?>
		<p class="small errormessage"><?php echo $this->error['enew_password']; ?></p>
		<?php } ?>
		<p class="input">
			<label for="f6" class="label"><?php echo $this->translate('Password'); ?> *<br class="hide" /></label>
			<input type="password" name="new_password" id="f6" value="" <?php echo isset($this->error['enew_password']) ? 'class="errorborder" ' : '' ;?>/>
			<a href="#" class="tooltip" title="<?php echo $this->translate('Choose a secured password for your account. Passwords such as \'123456\', \'password\' and \'xxxxxx\' are not recommended!') ;?>">?</a>
		</p>
		<?php if(isset($this->error['enew_password_confirm'])) { ?>
		<p class="small errormessage"><?php echo $this->error['enew_password_confirm']; ?></p>
		<?php } ?>
		<p class="input">
			<label for="f7" class="label"><?php echo $this->translate('Retype'); ?> *<br class="hide" /></label>
			<input type="password" name="new_password_confirm" id="f7" value="" <?php echo isset($this->error['enew_password_confirm']) ? 'class="errorborder" ' : '' ;?>/>
		</p>
		<p class="submit"><input type="submit" value="<?php echo $this->translate('Save Changes'); ?>" /></p>
	</form>
</div>
<?php echo $this->settings_box; ?>
<?php ob_start();?>
<script type="text/javascript">
$(document).ready(function() {
	head.ready("pass", function() {
		$.fn.shortPass = "<?php echo $this->translate('The password is too short'); ?>";
		$.fn.badPass = "<?php echo $this->translate('The password is not strong enough. Please type a more complicated password') ?>";
		$.fn.goodPass = "<?php echo $this->translate('The password is good'); ?>";
		$.fn.strongPass = "<?php echo $this->translate('The password is complicated. Well done!'); ?>";
		$.fn.samePassword = "<?php echo $this->translate('The password and the username are the same.') ?>";


		  $("#f6").parent().passStrength({
			password: "#f6",
			userid: "#f5",
			noteDiv: ""
		  });
	});
});
</script>
<?php $this->placeholder('inhead', ob_get_clean());?>