<div id="main" class="withhead">
	<h3 class="title-5"><?php echo $this->formtitle?></h3>
	<?php if(isset($this->msg_success)) { ?>
	<p id="msg" class="msg<?php echo isset($this->msg_success) ? ' box-success' : ''; ?>"><?php echo isset($this->msg_success) ? $this->msg_success : ''; ?></p>
	<?php } ?>
	<form action="" method="post" style="padding-top: 15px;" class="form">
		<?php $i = $j = 0; ?>
		<?php if($this->user['social']) { ?>
		<?php $cnt = count($this->user['social']); ?>
		<?php for(; $i < $cnt; $i++, $j++) { ?>
		<h3 class="social"><?php echo $this->user['social'][$i]['name']; ?><a href="#" onclick="javascript: if(confirm('<?php echo $this->translate('Are you sure you want to delete the profile?'); ?>')) {window.location.href='<?php echo WM_Router::create($this->getRequest()->getBaseUrl() .'?controller=users&action=edit&tool=social&sn='. ($i + 1)); ?>';} return false;" class="delete"></a></h3>
		<?php if(isset($this->error[$i]['social_name'])) { ?>
		<p class="small errormessage"><?php echo $this->error[$i]['social_name']; ?></p>
		<?php } ?>
		<p class="input">
			<label for="f<?php echo $j;?>" class="label"><?php echo $this->translate('Social media name'); ?> *<br class="hide" /></label>
			<input type="text" name="social_name[]" id="f<?php echo $j++;?>" value="<?php echo $this->user['social'][$i]['name']?>" <?php echo isset($this->error[$i]['social_name']) ? 'class="errorborder" ' : '' ;?>/>
			<a href="#" class="tooltip" title="<?php echo $this->translate('Full name of the social media') ;?>">?</a>
		</p>
		<?php if(isset($this->error[$i]['social_link'])) { ?>
		<p class="small errormessage"><?php echo $this->error[$i]['social_link']; ?></p>
		<?php } ?>
		<p class="input">
			<label for="f<?php echo $j;?>" class="label"><?php echo $this->translate('Profile link'); ?> *<br class="hide" /></label>
			<input type="text" name="social_link[]" id="f<?php echo $j; ?>" value="<?php echo $this->user['social'][$i]['href']; ?>" <?php echo isset($this->error[$i]['social_link']) ? 'class="errorborder" ' : '' ;?>/>
			<a href="#" class="tooltip" title="<?php echo $this->translate('Full link to your profile') ;?>">?</a>
		</p>
		<?php } ?>
		<?php } ?>
		<h3 class="social"><?php echo $this->translate('Add new profile'); ?></h3>
		<?php if(isset($this->error[$i]['social_name'])) { ?>
		<p class="small errormessage"><?php echo $this->error[$i]['social_name']; ?></p>
		<?php } ?>
		<p class="input">
			<label for="f<?php echo $j;?>" class="label"><?php echo $this->translate('Social media name'); ?> *<br class="hide" /></label>
			<input type="text" name="social_name[]" id="f<?php echo $j++;?>" value="<?php echo $this->new_user; ?>" <?php echo isset($this->error[$i]['social_name']) ? 'class="errorborder" ' : '' ;?>/>
			<a href="#" class="tooltip" title="<?php echo $this->translate('Full name of the social media') ;?>">?</a>
		</p>
		<?php if(isset($this->error[$i]['social_link'])) { ?>
		<p class="small errormessage"><?php echo $this->error[$i]['social_link']; ?></p>
		<?php } ?>
		<p class="input">
			<label for="f<?php echo $j;?>" class="label"><?php echo $this->translate('Profile link'); ?> *<br class="hide" /></label>
			<input type="text" name="social_link[]" id="f<?php echo $j++;?>" value="<?php echo $this->new_href; ?>" <?php echo isset($this->error[$i]['social_link']) ? 'class="errorborder" ' : '' ;?>/>
			<a href="#" class="tooltip" title="<?php echo $this->translate('Full link to your profile') ;?>">?</a>
		</p>
		<p class="submit"><input type="submit" value="<?php echo $this->translate('Save Changes'); ?>" /></p>
	</form>
</div>
<?php echo $this->settings_box; ?>