<?php echo $this->header_part; ?>

<div id="promo">
	<div class="welcome">
		<h1 class="title"><?php echo $this->translate('So sorry'); ?> <span><?php echo $this->translate('Page not found'); ?></span></h1>
		<p class="sheet"><img src="data/themes/images/missing-item_small.png" alt="404 <?php echo $this->translate('Error'); ?>" /></p>
		<div class="bluecircle">
			<h3>404</h3>
			<h4><?php echo $this->translate('Error'); ?></h4>
		</div>
		<ul class="features">
			<li><?php echo $this->translate('Page can not be displayed for the following reasons:')?></li>
			<li><?php echo $this->translate('This page has been removed;');?></li>
			<li><?php echo $this->translate('This page has been moved or her name has been changed;');?></li>
		</ul>
	</div>
</div>
<div id="content">
	<div class="viewall" style="z-index: 9560;">
		<p><?php echo $this->translate('URL, you are looking for can not be found');?></p>
	</div>
</div>

<?php echo $this->footer_part; ?>