<?php 
	$module = $this->getRequest()->getModule();
?>

<form name="admin_form" id="admin_form" method="post" action="" enctype="multipart/form-data">

	<div class="info_line top">
		<h3 class="fleft title">
			<img alt="" src="cms/<?php echo $module;?>/images/gallery-sml.png">
			<?php echo $this->translate('Smiles');?>
		</h3>
		
		<span id="fader" class="fleft mleft30" style="display:none;">
			<span class="msgError"><span><?php echo $this->translate('Error!');?></span><i class="error_text"></i></span>
		</span>
		
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/smiles/<?php echo ($this->page_num ? '?page=' . $this->page_num : '');?>"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>

	<div class="clear"></div>
	
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Name');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" title="<?php echo $this->translate('Please enter a name');?>" size="15" value="<?php echo $this->name;?>" class="inputbox required"  name="name" />
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Code');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" title="<?php echo $this->translate('Please enter a code');?>" size="15" value="<?php echo $this->code;?>" class="inputbox required"  name="code" />
        		</td>
			</tr>
			
			<tr>
				<td><?php echo $this->translate('Photo');?>:</td>
				<td>
					<input type="file" size="15" value="" class="inputbox"  name="photo" />
					<?php if($this->photo) { ?>
					<br /><br />
					<img src="uploads/<?php echo $this->photo;?>" alt="" />
					
					<input type="checkbox" value="yes" name="deletePhoto"> <?php echo $this->translate('Delete');?>
					<?php } ?>
        		</td>
			</tr>
			
			<tr>
				<td><?php echo $this->translate('Visible');?>: </td>
				<td>
					<select class="inputbox"  name="visible">
						<?php if($this->visible == 'true') { ?>
						<option selected="selected" value="true"><?php echo $this->translate('Yes');?></option>
						<option value="false"><?php echo $this->translate('No');?></option>
						<?php } else { ?>
						<option value="true"><?php echo $this->translate('Yes');?></option>
						<option selected="selected" value="false"><?php echo $this->translate('No');?></option>
						<?php } ?>
					</select>
        		</td>
			</tr>
			
		</tbody>
	</table>
		
	<div class="info_line bottom">
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/smiles/<?php echo ($this->page_num ? '?page=' . $this->page_num : '');?>"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
		
</form>