<?php 
	$module = $this->getRequest()->getModule();
?>
<form name="admin_form" id="admin_form" method="post" action="" enctype="multipart/form-data">

<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/<?php echo $module;?>/images/attributes.png">
		<?php echo $this->translate('Attributes');?> <?php echo ($this->parent_name ? ' › ' . $this->parent_name : '');?>
	</h3>
	
	<span id="fader" class="fleft mleft30" style="display:none;">
		<span class="msgError"><span><?php echo $this->translate('Error!');?></span><i class="error_text"></i></span>
	</span>
	
	<div class="fright mtop3">
		<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
		<a class="button" href="<?php echo $module;?>/attributes/<?php echo ($this->sub_of ? '?sub_of=' . $this->sub_of : '');?>"><?php echo $this->translate('Cancel');?></a>
	</div>
	<div class="clear"></div>
</div>

<div class="clear"></div>
		<table cellspacing="0" cellpadding="0" class="formtable">
			<tbody>
				<tr>
					<td width="150"><?php echo $this->translate('Name');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
					<td>
						<input type="text" title="<?php echo $this->translate('Please enter a name');?>" size="40" value="<?php echo $this->name;?>" class="inputbox required"  name="name" />
	        		</td>
				</tr>
				<?php if(!$this->sub_of) { ?>
				<tr>
					<td><?php echo $this->translate('Categories');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
					<td>
						<div class="scrollbox">
							<?php if($this->categories) { ?>
							<?php foreach($this->categories AS $key => $records_type) { ?>
							<div class="<?php echo ($key%2 ? 'odd' : 'even');?>">
								<?php if(in_array($records_type['id'], $this->categories_s)) { ?>
								<input class="record_type required" type="checkbox" checked="checked" value="<?php echo $records_type['id'];?>" name="categories[]"> <?php echo $records_type['name'];?>
								<?php } else { ?>
								<input class="record_type required" type="checkbox" value="<?php echo $records_type['id'];?>" name="categories[]"> <?php echo $records_type['name'];?>
								<?php } ?>
							</div>
							<?php } ?>
							<?php } ?>   
						</div>
						<br />
						<label style="position:static;margin-left:0;display:none;" for="categories[]" class="error"><?php echo $this->translate('Please select a category or categories!');?></label>
					</td>
				</tr>
				<tr>
					<td><?php echo $this->translate('Type');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
					<td>
						<select class="inputbox required"  name="type" title="<?php echo $this->translate('Please select a type');?>">
							<option value=""></option>
							<?php foreach($this->types AS $key => $value) { ?>
							<?php if($this->type == $key) { ?>
							<option selected="selected" value="<?php echo $key;?>"><?php echo $value;?></option>
							<?php } else { ?>
							<option value="<?php echo $key;?>"><?php echo $value;?></option>
							<?php } ?>
							<?php } ?>
						</select>
	        		</td>
				</tr>
				<?php } else { ?>
				<tr>
					<td><?php echo $this->translate('Photo');?>:</td>
					<td>
						<input type="file" size="15" value="" class="inputbox"  name="photo" />
						<?php if($this->photo) { ?>
						<br /><br />
						<img src="uploads/attributes/<?php echo $this->photo;?>" alt="" />
						
						<input type="checkbox" value="yes" name="deletePhoto"> <?php echo $this->translate('Delete');?>
						<?php } ?>
	        		</td>
				</tr>
				<?php } ?>
				<tr>
					<td><?php echo $this->translate('Visible');?>: </td>
					<td>
						<select class="inputbox"  name="visible">
							<?php if($this->visible == 'true') { ?>
							<option selected="selected" value="true"><?php echo $this->translate('Yes');?></option>
							<option value="false"><?php echo $this->translate('No');?></option>
							<?php } else { ?>
							<option value="true"><?php echo $this->translate('Yes');?></option>
							<option selected="selected" value="false"><?php echo $this->translate('No');?></option>
							<?php } ?>
						</select>
	        		</td>
				</tr>
				<tr>
					<td><?php echo $this->translate('Search');?>: </td>
					<td>
						<input type="checkbox" value="true" name="search" <?php echo $this->search == 'true' ? 'checked="checked"' : ''; ?>> <?php echo $this->sub_of == 0 ? $this->translate('all attributes in this category will be searchable') : $this->translate('this will be searchable');?>
	        		</td>
				</tr>
			</tbody>
		</table>
				
		<div class="info_line bottom">
			<div class="fright mtop3">
				<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
				<a class="button" href="<?php echo $module;?>/attributes/<?php echo ($this->sub_of ? '?sub_of=' . $this->sub_of : '');?>"><?php echo $this->translate('Cancel');?></a>
			</div>
			<div class="clear"></div>
		</div>
		
		<div class="clear"></div>
		
	</form>
	
<script type="text/javascript"> 
	$(document).ready(function(){
		$(".tabs ul").idTabs(); 
	});
</script>