<?php 
	$module = $this->getRequest()->getModule();
	ob_start();
?>
<link rel="stylesheet" type="text/css" href="cms/assets/vchecks/css/geogoer.vchecks.css" >
<script type="text/javascript" src="cms/assets/vchecks/jquery.vchecks.js"></script>
<script type="text/javascript">
	$(function(){
		$("#custom_list").vchecks();
	});
</script>
<?php $this->placeholder('scipts', ob_get_clean());?>
<form name="admin_form" id="admin_form" method="post" action="">

	<div class="info_line top">
		<h3 class="fleft title">
			<img alt="" src="cms/<?php echo $module;?>/images/gallery-sml.png">
			<?php echo $this->translate('Users Groups management');?>
		</h3>
		
		<span id="fader" class="fleft mleft30" style="display:none;">
			<span class="msgError"><span><?php echo $this->translate('Error');?>!</span><i class="error_text"></i></span>
		</span>
		
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/usergroups/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>

	<div class="clear"></div>
	
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Name');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" title="<?php echo $this->translate('Please enter a name');?>" size="15" value="<?php echo $this->name;?>" class="inputbox required"  name="name" />
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Description');?>: </td>
				<td>
					<textarea rows="4" cols="53" name="description" class="valid"><?php echo $this->description;?></textarea>
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Modules');?>: </td>
				<td>
					<ul id="custom_list" style="width: 100%;">
						<?php foreach($this->access_modules AS $group => $module1) { ?>
						<li>
							
								<?php if(array_key_exists($module1['key'], $this->access)) { ?>
								<input checked="checked" id="access-<?php echo $module1['key'];?>" name="access[<?php echo $module1['key'];?>]" value="on" type="checkbox" />
								<?php } else { ?>
								<input id="access-<?php echo $module1['key'];?>" name="access[<?php echo $module1['key'];?>]" value="on" type="checkbox" />
								<?php } ?>
								<span><?php echo $module1['name'];?></span>
						</li>
						<?php } ?>
					</ul>
        		</td>
			</tr>
		</tbody>
	</table>
		
	<div class="info_line bottom">
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/usergroups/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
		
</form>