<?php 
	$module = $this->getRequest()->getModule();
?>

<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/<?php echo $module;?>/images/gallery-sml.png">
		<?php echo $this->translate('Users Preview');?>
	</h3>
	
	<?php if($this->successfu_edite) { ?>
	<span id="fader" class="fleft mleft30"><span class="msgOk"><span><?php echo $this->translate('Successfully!');?></span><?php echo $this->translate('Information was successfully changed!');?></span></span>
	<script type="text/javascript"> 
	// <![CDATA[
	$(document).ready(function() {       
		setTimeout(function() {
			$("#fader").customFadeOut("slow" ,    
			function() {       
				$("#fader").remove();  
			});
		},
		4000);
	});
	// ]]>
	</script>
	<?php } ?>
	
	<?php /* ?>
	<div class="fright mtop3">
		<a class="button" href="<?php echo $module;?>/users/create/"><?php echo $this->translate('Add new');?></a>
	</div>
	<?php */ ?>
	<div class="clear"></div>
</div>



<p class="info">
	<?php echo $this->translate('User Manager');?>.<br>
	<strong><?php echo $this->translate('Note: If you delete an entry, information will be lost.');?></strong>
</p>

<form action="<?php echo $module;?>/users/" method="get" id="testtt">
<table cellspacing="0" cellpadding="0" class="display">
	<thead>
		<tr class="nodrop nodrag">
			<th width="20" class="left">
				<a href="<?php echo $this->sort_id;?>" <?php if($this->order == 'u.user_id') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>>#</a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_username;?>" <?php if($this->order == 'u.username') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Name');?></a>
			</th>
            
            <th class="left">
            	<a href="<?php echo $this->sort_total;?>" <?php if($this->order == 'u.total') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Currenet ballance');?></a>
            </th>
            <th class="left">
            	<a href="<?php echo $this->sort_sales;?>" <?php if($this->order == 'u.sales') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Sales');?></a>
            </th>
            <th class="left">
            	<a href="<?php echo $this->sort_sold;?>" <?php if($this->order == 'u.sold') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Sales profit');?></a>
            </th>
            <th class="left">
            	<a href="<?php echo $this->sort_web_profit2;?>" <?php if($this->order == 'web_profit2') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Website Profit');?></a>
            </th>
            <th class="left">
            	<?php echo $this->translate('Commission');?>
            </th>
            <th class="left">
            	<a href="<?php echo $this->sort_items;?>" <?php if($this->order == 'u.items') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Items');?></a>
            </th>
            <th class="left">
            	<a href="<?php echo $this->sort_referals;?>" <?php if($this->order == 'u.referals') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Referrals');?></a>
            </th>
            <th class="left">
            	<a href="<?php echo $this->sort_referal_money;?>" <?php if($this->order == 'u.referal_money') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Referal earnings');?></a>
            </th>
            <th class="left">
            	<a href="<?php echo $this->sort_featured_author;?>" <?php if($this->order == 'u.featured_author') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Featured Author');?></a>
            </th>
            
			<th width="20"><?php echo $this->translate('Edit');?></th>
            <th width="20"><?php echo $this->translate('Balance');?></th>
			<th width="20"><?php echo $this->translate('Delete');?></th>
		</tr>
		<tr class="search">
			<th class="left">
				<input class="inputbox" type="text" name="filter_id" value="<?php echo $this->filter_id;?>" size="4" />
			</th>
			<th class="left">
				<input class="inputbox filter_username" type="text" name="filter_username" value="<?php echo $this->filter_username;?>" size="8" />
			</th>
            
            <th class="left">
            	<input class="inputbox" type="text" name="filter_total" value="<?php echo $this->filter_total;?>" size="5" />
            </th>
            <th class="left">
            	<input class="inputbox" type="text" name="filter_sales" value="<?php echo $this->filter_sales;?>" size="5" />
            </th>
            <th class="left">
            	<input class="inputbox" type="text" name="filter_sold" value="<?php echo $this->filter_sold;?>" size="5" />
            </th>
            <th class="left">
            	<input class="inputbox" type="text" name="filter_web_profit2" value="<?php echo $this->filter_web_profit2;?>" size="5" />
            </th>
            <th class="left"></th>
            <th class="left">
            	<input class="inputbox" type="text" name="filter_items" value="<?php echo $this->filter_items;?>" size="5" />
            </th>
            <th class="left">
            	<input class="inputbox" type="text" name="filter_referals" value="<?php echo $this->filter_referals;?>" size="5" />
            </th>
            <th class="left">
            	<input class="inputbox" type="text" name="filter_referal_money" value="<?php echo $this->filter_referal_money;?>" size="5" />
            </th>
            <th class="left">
            	<select name="filter_featured_author" class="inputbox" style="width: 60px;">
					<?php if($this->filter_featured_author == 'true') { ?>
					<option value=""></option>
					<option selected="selected" value="true"><?php echo $this->translate('Yes');?></option>
					<option value="false"><?php echo $this->translate('No');?></option>
					<?php } elseif($this->filter_featured_author == 'false') { ?>
					<option value=""></option>
					<option value="true"><?php echo $this->translate('Yes');?></option>
					<option selected="selected" value="false"><?php echo $this->translate('No');?></option>
					<?php } else { ?>
					<option value=""></option>
					<option value="true"><?php echo $this->translate('Yes');?></option>
					<option value="false"><?php echo $this->translate('No');?></option>
					<?php } ?>
				</select>
            </th>
            
			<th colspan="3">
				<input type="submit" value="<?php echo $this->translate('Filter');?>" class="button">
				&nbsp; <a href="<?php echo $module;?>/users/"><img src="cms/<?php echo $module;?>/images/reload.png" class="tooltip"  alt="" title="<?php echo $this->translate('Reset');?>" /></a>
			</th>
		</tr>
	</thead>
	<tbody>
	<?php if($this->users) { ?>
	<?php foreach($this->users AS $user) { ?>
		<tr id="<?php echo $user['user_id'];?>">
			<td><?php echo $user['user_id'];?>.</td>
			<td>
				<?php echo $user['username'];?> 
			</td>
            
            <td><?php echo $user['total'];?> </td>
            <td><?php echo $user['sales'];?> </td>
            <td><?php echo $user['sold'];?> </td>
            
            <td>
            	<?php if($user['has_referral_sum'] > 0) { ?>
					<a class="tooltip" title="<?php echo $this->translate('Website receive');?> <?php echo $user['web_profit'];?> - <?php echo $this->translate('Seller referral receive');?> <?php echo $user['referral_sum'];?> = <?php echo $user['web_profit2'];?>"><?php echo $user['web_profit2'];?></a>
				<?php } else { ?>
					<?php echo $user['web_profit2'];?>
				<?php } ?>
            </td>
            
            <td align="center"><?php echo $user['commission'];?> % </td>
            <td align="center">
                <a href="<?php echo $module;?>/items/?filter_user_id=<?php echo $user['user_id'];?>"><?php echo $user['items'];?></a>
            </td>
            <td align="center"><?php echo $user['referal_cnt'];?> </td>
            <td><?php echo $user['referal_money'];?> </td>
            <td align="center">
            	<a href="javascript:void(0);" onclick="changeAuthor(<?php echo $user['user_id'];?>);">
                	<img title="<?php echo ($user['featured_author'] == 'true' ? 'yes' : 'no');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/<?php echo ($user['featured_author'] == 'true' ? 'yes' : 'no');?>.png"> 
            	</a>
            </td>
            
			<td align="center"><a href="<?php echo $user['edit_href'];?>"><img title="<?php echo $this->translate('Edit');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/edit.png"></a></td>
            <td align="center"><a href="<?php echo $user['balance_href'];?>"><?php echo $this->translate('Balance');?> (<?php echo $user['sum']['paid'];?> / <?php echo $user['sum']['not_paid'];?>)</a></td>
			<td align="center">
				<?php if(JO_Session::get('user_id') != $user['user_id']) {?>
				<a id="item_<?php echo $user['user_id'];?>" class="delete" href="javascript:void(0);"><img title="<?php echo $this->translate('Delete');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/delete.png"></a>
				<?php } ?>
			</td>
		</tr>
	<?php } ?>
	<?php } else { ?>
		<tr class="nodrop nodrag">
			<td colspan="14">
				<div class="msgAlert"><span><?php echo $this->translate('Attention!');?></span><?php echo $this->translate('No records found ...');?></div>
			</td>
		</tr>
	<?php } ?>
	</tbody>
</table>
</form>
<?php if($this->pagination) { ?>
<br />
<div class="fleft">
<?php echo $this->translate('Page');?> <b><?php echo $this->page_num;?></b> <?php echo $this->translate('from');?> <b><?php echo $this->total_pages;?></b> (<b><?php echo $this->total_rows;?></b> <?php echo $this->translate('records');?>)
</div>
<div class="pagination fright">
	<?php echo $this->pagination;?>
</div>
<div class="clear"></div>
<?php } ?>

<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function() {       
	$('a.delete').click(function (e) {
        if (confirm(lang.confirm)) {
            e.preventDefault();
            var parent = $(this).parents('tr');
            $.ajax({
                type: 'post',
                url: "<?php echo $module;?>/users/delete/",
                data: 'id=' + $(this).attr('id').replace('item_', ''),
                beforeSend: function () {
                    parent.animate({
                        'backgroundColor': '#FFBFBF'
                    }, 400);
                },
                success: function () {
                    parent.fadeOut(400, function () {
                        parent.remove();
                    });
                }
            });
        }
    });
});
// ]]>
</script>

<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function(){
	var cache = {},
	lastXhr;
	$( ".filter_username" ).autocomplete({
		minLength: 2,
		source: function( request, response ) {
			var term = request.term;
			if ( term in cache ) {
				response( cache[ term ] );
				return;
			}
	
			lastXhr = $.getJSON( "<?php echo $module;?>/users/liveSearch/?filter=user", request, function( data, status, xhr ) {
				cache[ term ] = data;
				if ( xhr === lastXhr ) {
					response( data );
				}
			});
		}
	});
});
//]]>
</script>

<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function(){
	$('#testtt').submit(function(){
		window.location = $('#testtt').joform();
		return false;
	});
});

$(document).ready(function() {       
	deleteInit();
});

function deleteInit() {
	$('a.delete').click(function (e) {
        if (confirm(lang.confirm)) {
            e.preventDefault();
            var parent = $(this).parents('tr');
            $.ajax({
                type: 'post',
                url: "<?php echo $module;?>/membership/delete/",
                data: 'id=' + $(this).attr('id').replace('item_', ''),
                beforeSend: function () {
                    parent.animate({
                        'backgroundColor': '#FFBFBF'
                    }, 400);
                },
                success: function () {
                    parent.fadeOut(400, function () {
                        parent.remove();
                    });
                }
            });
        }
    });
}

changeAuthor = function(id) {
	$.ajax({
        type: 'post',
        url: "<?php echo $module;?>/users/changeAuthor",
        data: 'id=' + id,
        beforeSend: function () {
			$('#'+id).animate({
                'backgroundColor': '#FFBFBF'
            }, 400);
        },
        success: function () {
        	$.get(window.location.href, function(data){
        		$('#'+id).html($(data).find('#'+id).html());
        		setTimeout(function(){
        			$("#"+id+"").animate({'backgroundColor': 'transparent'}, 400).find('.tooltip').simpletooltip();
        			deleteInit();
        		}, 500);
        	});
        }
	});
};
//]]>
</script>