<?php 
	$module = $this->getRequest()->getModule();
?>
<form name="admin_form" id="admin_form" method="post" action="" enctype="multipart/form-data">
	<div class="info_line top">
		<h3 class="fleft title">
			<img alt="" src="cms/<?php echo $module;?>/images/percents.png">
			<?php echo $this->translate('Membership Management');?>
		</h3>
		<span id="fader" class="fleft mleft30" style="display:none;">
			<span class="msgError"><span><?php echo $this->translate('Error!');?></span><i class="error_text"></i></span>
		</span>
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/membership/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Status');?>: </td>
				<td>
					<select name="status">
						<?php if($this->status == 'true') { ?>
						<option selected="selected" value="true"><?php echo $this->translate('Enabled');?></option>
						<option value="false"><?php echo $this->translate('Disabled');?></option>
						<?php } else { ?>
						<option value="true"><?php echo $this->translate('Enabled');?></option>
						<option selected="selected" value="false"><?php echo $this->translate('Disabled');?></option>
						<?php } ?>
					</select>
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Name');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" title="<?php echo $this->translate('Please enter name');?>" size="40" value="<?php echo $this->name;?>" class="inputbox required"  name="name" />
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Position');?>: </td>
				<td>
					<input type="text" title="<?php echo $this->translate('Please enter position number');?>" size="15" value="<?php echo $this->order_index;?>" class="inputbox"  name="order_index" />
        		</td>
			</tr>
		</tbody>
	</table>
	<div class="info_line bottom">
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/membership/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>	
</form>