<?php 
	$module = $this->getRequest()->getModule();
?>
<form name="admin_form" id="admin_form" method="post" action="">
<input type="hidden" name="send_to" value="site" />

<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/<?php echo $module;?>/images/contacts.png">
		<?php echo $this->translate('Bulletin');?>
	</h3>
	
	<span id="fader" class="fleft mleft30" style="display:none;">
		<span class="msgError"><span><?php echo $this->translate('Error!');?></span><i class="error_text"></i></span>
	</span>
	
	<div class="fright mtop3">
		<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
		<a class="button" href="<?php echo $module;?>/bulletin/?page=<?php echo $this->page_num;?>"><?php echo $this->translate('Cancel');?></a>
	</div>
	<div class="clear"></div>
</div>

<div class="clear"></div>

	
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Name');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" title="<?php echo $this->translate('Please enter a name');?>" size="40" value="<?php echo $this->name;?>" class="inputbox required"  name="name" />
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Description');?>: </td>
				<td>
					<textarea rows="4" cols="53" name="text" class="valid ckeditor_replace"><?php echo $this->text;?></textarea>
        		</td>
			</tr>
		</tbody>
	</table>

	
	<div class="info_line bottom">
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/bulletin/?page=<?php echo $this->page_num;?>"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
	
	<div class="clear"></div>
	
</form>