<?php 
	$module = $this->getRequest()->getModule();
?>

<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/<?php echo $module;?>/images/contacts.png">
		<?php echo $this->translate('Bulletin');?>
	</h3>
	
	<?php if($this->successfu_edite) { ?>
	<span id="fader" class="fleft mleft30"><span class="msgOk"><span><?php echo $this->translate('Successfully!');?></span><?php echo $this->translate('Information was successfully changed!');?></span></span>
	<script type="text/javascript"> 
	// <![CDATA[
	$(document).ready(function() {       
		setTimeout(function() {
			$("#fader").customFadeOut("slow" ,    
			function() {       
				$("#fader").remove();  
			});
		},
		4000);
	});
	// ]]>
	</script>
	<?php } ?>
	
	<div class="fright mtop3">
		<a class="button" href="<?php echo $module;?>/bulletin/create/?page=<?php echo $this->page_num;?>"><?php echo $this->translate('Add new bulletin');?></a>
	</div>
	<div class="clear"></div>
</div>


<p class="info">
	<?php echo $this->translate('Bulletin Manager');?>.<br>
</p>


<table cellspacing="0" cellpadding="0" class="display">
	<thead>
		<tr class="nodrop nodrag">
			<th width="20" class="left">#</th>
			<th class="left"><?php echo $this->translate('Name');?></th>
			<th class="left"><?php echo $this->translate('Send to');?></th>
			<th width="20"><?php echo $this->translate('Action');?></th>
		</tr>
	</thead>
	<tbody>
	<?php if($this->bulletines) { ?>
	<?php foreach($this->bulletines AS $bulletin) { ?>
		<tr id="<?php echo $bulletin['id'];?>">
			<td><?php echo $bulletin['id'];?>.</td>
			<td><?php echo $bulletin['name'];?></td>
			<td><?php echo $bulletin['readed'];?></td>
			<td align="center">
				<a href="<?php echo $module;?>/bulletin/view/?id=<?php echo $bulletin['id'];?>&page=<?php echo $this->page_num;?>">
					<img title="<?php echo $this->translate('View');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/view.png">
				</a>
			</td>
		</tr>
	<?php } ?>
	<?php } else { ?>
		<tr class="nodrop nodrag">
			<td colspan="4">
				<div class="msgAlert"><span><?php echo $this->translate('Attention!');?></span><?php echo $this->translate('No records found ...');?></div>
			</td>
		</tr>
	<?php } ?>
	</tbody>
</table>
<?php if($this->pagination) { ?>
<br />
<div class="fleft">
<?php echo $this->translate('Page');?> <b><?php echo $this->page_num;?></b> <?php echo $this->translate('from');?> <b><?php echo $this->total_pages;?></b> (<b><?php echo $this->total_rows;?></b> <?php echo $this->translate('records');?>)
</div>
<div class="pagination fright">
	<?php echo $this->pagination;?>
</div>
<div class="clear"></div>
<?php } ?>
