<?php 
	$module = $this->getRequest()->getModule();
?>

<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/<?php echo $module;?>/images/ordering.png">
		<?php echo $this->translate('Sales');?>
	</h3>
	
	<?php if($this->successfu_edite) { ?>
	<span id="fader" class="fleft mleft30"><span class="msgOk"><span><?php echo $this->translate('Successfully!');?></span><?php echo $this->translate('Information was successfully changed!');?></span></span>
	<script type="text/javascript"> 
	// <![CDATA[
	$(document).ready(function() {       
		setTimeout(function() {
			$("#fader").customFadeOut("slow" ,    
			function() {       
				$("#fader").remove();  
			});
		},
		4000);
	});
	// ]]>
	</script>
	<?php } ?>
	
	<div class="fright mtop3">
		<a class="button" href="javascript:void(0);" onclick="multiActionSelected('deleteMulti');"><?php echo $this->translate('Delete selected');?></a>
	</div>
	<div class="clear"></div>
</div>
<p class="info">
	<?php echo $this->translate('Sales Manager');?>.<br>
	<strong><?php echo $this->translate('Note: If you delete an entry, information will be lost.');?></strong>
</p>
<div class="tabs mtop3">
	<ul>
		<li><a href="<?php echo $this->order_link; ?>" class="selected"><?php echo $this->translate('Orders');?></a></li>
		<li><a href="<?php echo $this->deposit_link; ?>"><?php echo $this->translate('Deposit');?></a></li>
		<li><a href="<?php echo $this->membership_link; ?>"><?php echo $this->translate('Membership');?></a></li>
	</ul> 
	<div class="clear"></div>
</div>
<form action="<?php echo $module;?>/orders/" method="get" id="testtt">
<?php if($this->filter_order_id) { ?>
<input type="hidden" name="filter_order_id" value="<?php echo $this->filter_order_id;?>" />
<?php } ?>
<table cellspacing="0" cellpadding="0" class="display" id="table_change">
	<thead>
		<tr>
			<th width="20">
				<input type="checkbox" class="check_all_list" />
			</th>
			<th width="20" class="left">
				<a href="<?php echo $this->sort_id;?>" <?php if($this->order == 'o.id') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>>#</a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_name;?>" <?php if($this->order == 'o.name') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Item');?></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_username;?>" <?php if($this->order == 'u.username') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Buyer');?></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_owner;?>" <?php if($this->order == 'u2.username') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Seller');?></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_price;?>" <?php if($this->order == 'o.price') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Price');?></a>
			</th>
			<?php if($this->filter_type == 'buy') { ?>
			<th class="left">
				<a href="<?php echo $this->sort_web_receive;?>" <?php if($this->order == 'web_profit') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Website receive');?></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_receive;?>" <?php if($this->order == 'o.receive') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Seller receive');?></a>
			</th>
			<?php } else { ?>
			<th class="left">
				<a href="<?php echo $this->sort_receive;?>" <?php if($this->order == 'o.receive') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Seller referral receive');?></a>
			</th>
			<?php } ?>
			<th class="left">
				<a href="<?php echo $this->sort_datetime;?>" <?php if($this->order == 'o.datetime') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Ordered on');?></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_paid;?>" <?php if($this->order == 'o.paid') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Payed');?></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_paid_datetime;?>" <?php if($this->order == 'o.paid_datetime') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Order date');?></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_extended;?>" <?php if($this->order == 'o.extended') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Extended license');?></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_type;?>" <?php if($this->order == 'o.type') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Type');?></a>
			</th>
			<th width="20"><?php echo $this->translate('Delete');?></th>
		</tr>
		<tr class="search">
			<th class="left" colspan="2">
				<input class="inputbox" type="text" name="filter_id" value="<?php echo $this->filter_id;?>" size="4" />
			</th>
			<th class="left">
				<input class="inputbox item_title" type="text" name="filter_name" value="<?php echo $this->filter_name;?>" size="15" />
			</th>
			<th class="left">
				<input class="inputbox item_username" type="text" name="filter_username" value="<?php echo $this->filter_username;?>" size="6" />
			</th>
			<th class="left">
				<input class="inputbox item_username" type="text" name="filter_owner" value="<?php echo $this->filter_owner;?>" size="6" />
			</th>
			<th class="left">
				<input class="inputbox" type="text" name="filter_price" value="<?php echo $this->filter_price;?>" size="5" />
			</th>
			<?php if($this->filter_type == 'buy') { ?>
			<th class="left">
				<input class="inputbox" type="text" name="filter_web_receive" value="<?php echo $this->filter_web_receive;?>" size="3" />
			</th>
			<?php } ?>
			<th class="left">
				<input class="inputbox" type="text" name="filter_receive" value="<?php echo $this->filter_receive;?>" size="3" />
			</th>
			<th class="left">
				<input class="inputbox datepicer" id="from_date" type="text" name="filter_from" value="<?php echo $this->filter_from;?>" size="5" /> - 
				<input class="inputbox datepicer" type="text" name="filter_to" value="<?php echo $this->filter_to;?>" size="5" />
			</th>
			<th class="left">
				<select name="filter_paid" class="inputbox" style="width: 60px;">
					<?php if($this->filter_paid == 'true') { ?>
					<option value=""></option>
					<option selected="selected" value="true"><?php echo $this->translate('Yes');?></option>
					<option value="false"><?php echo $this->translate('No');?></option>
					<?php } elseif($this->filter_paid == 'false') { ?>
					<option value=""></option>
					<option value="true"><?php echo $this->translate('Yes');?></option>
					<option selected="selected" value="false"><?php echo $this->translate('No');?></option>
					<?php } else { ?>
					<option value=""></option>
					<option value="true"><?php echo $this->translate('Yes');?></option>
					<option value="false"><?php echo $this->translate('No');?></option>
					<?php } ?>
				</select>
			</th>
			<th class="left">
				<input class="inputbox datepicer2" id="from_date2" type="text" name="filter_paid_from" value="<?php echo $this->filter_paid_from;?>" size="5" /> - 
				<input class="inputbox datepicer2" type="text" name="filter_paid_to" value="<?php echo $this->filter_paid_to;?>" size="5" />
			</th>
			<th class="left">
				<select name="filter_extended" class="inputbox" style="width: 60px;">
					<?php if($this->filter_extended == 'true') { ?>
					<option value=""></option>
					<option selected="selected" value="true"><?php echo $this->translate('Yes');?></option>
					<option value="false"><?php echo $this->translate('No');?></option>
					<?php } elseif($this->filter_extended == 'false') { ?>
					<option value=""></option>
					<option value="true"><?php echo $this->translate('Yes');?></option>
					<option selected="selected" value="false"><?php echo $this->translate('No');?></option>
					<?php } else { ?>
					<option value=""></option>
					<option value="true"><?php echo $this->translate('Yes');?></option>
					<option value="false"><?php echo $this->translate('No');?></option>
					<?php } ?>
				</select>
			</th>
			<th class="left">
				<select name="filter_type" class="inputbox" style="width: 60px;">
					<?php if($this->filter_type == 'buy') { ?>
					<option value=""></option>
					<option selected="selected" value="buy"><?php echo $this->translate('Buy');?></option>
					<option value="referal"><?php echo $this->translate('Referal');?></option>
					<?php } elseif($this->filter_type == 'referal') { ?>
					<option value=""></option>
					<option value="buy"><?php echo $this->translate('Buy');?></option>
					<option selected="selected" value="referal"><?php echo $this->translate('Referal');?></option>
					<?php } else { ?>
					<option value=""></option>
					<option value="buy"><?php echo $this->translate('Buy');?></option>
					<option value="referal"><?php echo $this->translate('Referal');?></option>
					<?php } ?>
				</select>
			</th>
			<th>
				<input type="submit" value="<?php echo $this->translate('Filter');?>" class="button">
				&nbsp; <a href="<?php echo $module;?>/orders/"><img src="cms/<?php echo $module;?>/images/reload.png" class="tooltip"  alt="" title="<?php echo $this->translate('Reset');?>" /></a>
			</th>
		</tr>
	</thead>
	<tbody>
	<?php if($this->items) { ?>
	<?php foreach($this->items AS $item) { ?>
		<tr id="<?php echo $item['id'];?>">
			<td>
				<?php if(!$item['paid']) { ?>
				<input type="checkbox" class="check_list" name="action_check[]" value="<?php echo $item['id'];?>" />
				<?php } ?>
			</td>
			<td><?php echo $item['id'];?>.</td>
			<td>
				<a href="<?php echo $item['href'];?>" target="_blank"><?php echo $item['name'];?></a>
				<?php if($item['has_referal']) { ?>
				<a href="<?php echo $module;?>/orders/?filter_order_id=<?php echo $item['id'];?>&filter_type=referal" target="_blank">
					<img class="tooltip" src="cms/<?php echo $module;?>/images/external-link.png" alt="<?php echo $this->translate('Referal'); ?>" title="<?php echo $this->translate('Referal'); ?>" />
				</a>
				<?php } elseif($item['has_buy']) { ?>
				<a href="<?php echo $module;?>/orders/?filter_id=<?php echo $item['order_id'];?>&filter_type=buy" target="_blank">
					<img class="tooltip" src="cms/<?php echo $module;?>/images/flag.png" alt="<?php echo $this->translate('Buy'); ?>" title="<?php echo $this->translate('Buy'); ?>" />
				</a>
				<?php } ?>
			</td>
			<td><?php echo $item['username'];?></td>
			<td><?php echo $item['owner'];?></td>
			<td><?php echo $item['price'];?></td>
			<?php if($this->filter_type == 'buy') { ?>
			<td>
				<?php if($item['has_referral_sum']) { ?>
					<a class="tooltip" title="<?php echo $this->translate('Website receive');?> <?php echo $item['web_profit'];?> - <?php echo $this->translate('Seller referral receive');?> <?php echo $item['referral_sum'];?> = <?php echo $item['web_profit2'];?>"><?php echo $item['web_profit2'];?></a>
				<?php } else { ?>
					<?php echo $item['web_profit2'];?>
				<?php } ?>
			</td>
			<?php } ?>
			<td><?php echo $item['profit'];?></td>
			<td><?php echo $item['datetime'];?></td>
			<td align="center">
				<a href="javascript:void(0);" onclick="changeStatus(<?php echo $item['id'];?>);">
					<img src="cms/<?php echo $module;?>/images/<?php echo ($item['paid'] ? 'yes.png' : 'no.png');?>" class="tooltip"  alt="" title="<?php echo ($item['paid'] ? $this->translate('Yes') : $this->translate('No'));?>" />
				</a>
			</td>
			<td><?php echo $item['paid_datetime'];?></td>
			<td align="center">
				<img src="cms/<?php echo $module;?>/images/<?php echo ($item['extended'] ? 'yes.png' : 'no.png');?>" class="tooltip"  alt="" title="<?php echo ($item['extended'] ? $this->translate('Yes') : $this->translate('No'));?>" />
			</td>
			<td><?php echo ($item['type'] == 'buy' ? $this->translate('Buy') : $this->translate('Referal'));?></td>
			<td align="center">
				<?php if(!$item['paid']) { ?>
				<a id="item_<?php echo $item['id'];?>" class="delete" href="javascript:void(0);"><img title="<?php echo $this->translate('Delete');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/delete.png"></a>
				<?php } ?>
			</td>
		</tr>
	<?php } ?>
		<tr>
			<td colspan="5"><?php echo $this->translate('Total');?>:</td>
			<td style="font-weight: bold;"><?php echo $this->price;?></td>
			<?php if($this->filter_type == 'buy') { ?>
			<td style="font-weight: bold;"><?php echo $this->web_profit2;?></td>
			<?php } ?>
			<td style="font-weight: bold;"><?php echo $this->profit;?></td>
			<td colspan="6"></td>
		</tr>
	<?php } else { ?>
		<tr>
			<td colspan="<?php echo ($this->filter_type == 'buy' ? 14 : 13);?>">
				<div class="msgAlert"><span><?php echo $this->translate('Attention!');?></span><?php echo $this->translate('No records found ...');?></div>
			</td>
		</tr>
	<?php } ?>
	</tbody>
</table>
</form>
<?php if($this->pagination) { ?>
<br />
<div class="fleft">
<?php echo $this->translate('Page');?> <b><?php echo $this->page_num;?></b> <?php echo $this->translate('from');?> <b><?php echo $this->total_pages;?></b> (<b><?php echo $this->total_rows;?></b> <?php echo $this->translate('records');?>)
</div>
<div class="pagination fright">
	<?php echo $this->pagination;?>
</div>
<div class="clear"></div>
<?php } ?>

<script type="text/javascript"> 
changeStatus = function(id) {
	$.ajax({
        type: 'post',
        url: "<?php echo $module;?>/orders/changeStatus",
        data: 'id=' + id,
        beforeSend: function () {
			$('#'+id).animate({
                'backgroundColor': '#FFBFBF'
            }, 400);
        },
        success: function () {
        	$.get(window.location.href, function(data){
            	var html = $(data).find('#table_change');
            	html.find("#"+id+"").css({'backgroundColor': '#FFBFBF'});
        		$('#table_change').html(html.html());
        		setTimeout(function(){
        			$("#"+id+"").animate({'backgroundColor': 'transparent'}, 400).find('.tooltip').simpletooltip();
        			deleteInit();
        		}, 500);
        	});
        }
	});
};
//]]>
</script>
<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function(){
	var cache = {},
	lastXhr;
	$( ".item_title" ).autocomplete({
		minLength: 2,
		source: function( request, response ) {
			var term = request.term;
			if ( term in cache ) {
				response( cache[ term ] );
				return;
			}
	
			lastXhr = $.getJSON( "<?php echo $module;?>/orders/liveSearch/?filter=item", request, function( data, status, xhr ) {
				cache[ term ] = data;
				if ( xhr === lastXhr ) {
					response( data );
				}
			});
		}
	});
});
//]]>
</script>
<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function(){
	var cache = {},
	lastXhr;
	$( ".item_username" ).autocomplete({
		minLength: 2,
		source: function( request, response ) {
			var term = request.term;
			if ( term in cache ) {
				response( cache[ term ] );
				return;
			}
	
			lastXhr = $.getJSON( "<?php echo $module;?>/orders/liveSearch/?filter=user", request, function( data, status, xhr ) {
				cache[ term ] = data;
				if ( xhr === lastXhr ) {
					response( data );
				}
			});
		}
	});
});
//]]>
</script>
<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function(){
	var dates = $( ".datepicer" ).datepicker({
		dateFormat : 'dd.mm.yy',
		numberOfMonths: 1,
		onSelect: function( selectedDate ) {
			var option = this.id == "from_date" ? "minDate" : "maxDate",
				instance = $( this ).data( "datepicker" ),
				date = $.datepicker.parseDate(
					instance.settings.dateFormat ||
					$.datepicker._defaults.dateFormat,
					selectedDate, instance.settings );
			dates.not( this ).datepicker( "option", option, date );
		}
	});

	var dates2 = $( ".datepicer2" ).datepicker({
		dateFormat : 'dd.mm.yy',
		numberOfMonths: 1,
		onSelect: function( selectedDate2 ) {
			var option2 = this.id == "from_date2" ? "minDate" : "maxDate",
				instance2 = $( this ).data( "datepicker" ),
				date2 = $.datepicker.parseDate(
					instance2.settings.dateFormat ||
					$.datepicker._defaults.dateFormat,
					selectedDate2, instance2.settings );
			dates2.not( this ).datepicker( "option", option2, date2 );
		}
	});
});
//]]>
</script>
<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function(){
	$('#testtt').submit(function(){
		window.location = $('#testtt').joform();
		return false;
	});
});
//]]>
</script>
<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function(){
	deleteInit();
});
//]]>
</script>
<script type="text/javascript"> 
// <![CDATA[
function deleteInit() {
	$('a.delete').click(function (e) {
        if (confirm(lang.confirm)) {
            e.preventDefault();
            var parent = $(this).parents('tr');
            $.ajax({
                type: 'post',
                url: "<?php echo $module;?>/orders/delete",
                data: 'id=' + $(this).attr('id').replace('item_', ''),
                beforeSend: function () {
                    parent.animate({
                        'backgroundColor': '#FFBFBF'
                    }, 400);
                },
                success: function () {
                    parent.fadeOut(400, function () {
                        parent.remove();
                    });
                }
            });
        }
    });
}
// ]]>
</script>