<?php 
	$module = $this->getRequest()->getModule();
?>

<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/<?php echo $module;?>/images/ordering.png">
		<?php echo $this->translate('Sales');?>
	</h3>
	
	<?php if($this->successfu_edite) { ?>
	<span id="fader" class="fleft mleft30"><span class="msgOk"><span><?php echo $this->translate('Successfully!');?></span><?php echo $this->translate('Information was successfully changed!');?></span></span>
	<script type="text/javascript"> 
	// <![CDATA[
	$(document).ready(function() {       
		setTimeout(function() {
			$("#fader").customFadeOut("slow" ,    
			function() {       
				$("#fader").remove();  
			});
		},
		4000);
	});
	// ]]>
	</script>
	<?php } ?>
	
	<div class="fright mtop3">
		<a class="button" href="javascript:void(0);" onclick="multiActionSelected('deleteMultiMembership');"><?php echo $this->translate('Delete selected');?></a>
	</div>
	<div class="clear"></div>
</div>


<p class="info">
	<?php echo $this->translate('Sales Manager');?>.<br>
	<strong><?php echo $this->translate('Note: If you delete an entry, information will be lost.');?></strong>
</p>
<div class="tabs mtop3">
	<ul>
		<li><a href="<?php echo $this->order_link; ?>"><?php echo $this->translate('Orders');?></a></li>
		<li><a href="<?php echo $this->deposit_link; ?>"><?php echo $this->translate('Deposit');?></a></li>
		<li><a href="<?php echo $this->membership_link; ?>" class="selected"><?php echo $this->translate('Membership');?></a></li>
	</ul> 
	<div class="clear"></div>
</div>
<form action="<?php echo $module;?>/orders/membership" method="get" id="testtt">
<?php if($this->filter_order_id) { ?>
<input type="hidden" name="filter_order_id" value="<?php echo $this->filter_order_id;?>" />
<?php } ?>
<table cellspacing="0" cellpadding="0" class="display" id="table_change">
	<thead>
		<tr>
			<th width="20">
				<input type="checkbox" class="check_all_list" />
			</th>
			<th width="20" class="left">
				<a href="<?php echo $this->sort_id;?>" <?php if($this->order == 'm.id') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_username;?>" <?php if($this->order == 'u.username') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('User');?></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_price;?>" <?php if($this->order == 'm.amount') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Sum');?></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_datetime;?>" <?php if($this->order == 'm.datetime') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Order date');?></a>
			</th>
			<th class="left">
				<?php echo $this->translate('Payment');?>
			</th>
			<th align="center">
				<?php echo $this->translate('Paid');?>
			</th>
			<th width="20"><?php echo $this->translate('Delete');?></th>
		</tr>
		<tr class="search">
			<th class="left" colspan="2">
				<input class="inputbox" type="text" name="filter_id" value="<?php echo $this->filter_id;?>" size="4" />
			</th>
			<th class="left">
				<input class="inputbox item_username" type="text" name="filter_username" value="<?php echo $this->filter_username;?>" size="6" />
			</th>
			<th class="left">
				<input class="inputbox" type="text" name="filter_price" value="<?php echo $this->filter_price;?>" size="5" />
			</th>
			<th class="left"></th>
			<th class="left"></th>
			<th class="left"></th>
			<th>
				<input type="submit" value="<?php echo $this->translate('Filter');?>" class="button">
				&nbsp; <a href="<?php echo $module;?>/orders/"><img src="cms/<?php echo $module;?>/images/reload.png" class="tooltip"  alt="" title="<?php echo $this->translate('Reset');?>" /></a>
			</th>
		</tr>
	</thead>
	<tbody>
	<?php if($this->items) { ?>
	<?php foreach($this->items AS $item) { ?>
		<tr id="<?php echo $item['id'];?>">
			<td>
				<input type="checkbox" class="check_list" name="action_check[]" value="<?php echo $item['id'];?>" />
			</td>
			<td>#<?php echo $item['id'];?></td>
			<td><?php echo $item['username'];?></td>
			<td><?php echo $item['amount'];?></td>
			<td><?php echo $item['datetime'];?></td>
			<td><?php echo (!empty($item['paid_from']) ? $item['paid_from'] : $this->translate('Unknown')); ?></td>
			<td align="center">
				<a href="javascript:void(0);" onclick="changeStatus(<?php echo $item['id'];?>);">
					<img src="cms/admin/images/no.png" class="tooltip"  alt="" title="<?php echo $this->translate('No'); ?>" />
				</a>
			</td>
			<td align="center">
				<a id="item_<?php echo $item['id'];?>" class="delete" href="javascript:void(0);"><img title="<?php echo $this->translate('Delete');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/delete.png"></a>
			</td>
		</tr>
	<?php } ?>
	<?php } else { ?>
		<tr>
			<td colspan="8">
				<div class="msgAlert"><span><?php echo $this->translate('Attention!');?></span><?php echo $this->translate('No records found ...');?></div>
			</td>
		</tr>
	<?php } ?>
	</tbody>
</table>
</form>
<?php if($this->pagination) { ?>
<br />
<div class="fleft">
<?php echo $this->translate('Page');?> <b><?php echo $this->page_num;?></b> <?php echo $this->translate('from');?> <b><?php echo $this->total_pages;?></b> (<b><?php echo $this->total_rows;?></b> <?php echo $this->translate('records');?>)
</div>
<div class="pagination fright">
	<?php echo $this->pagination;?>
</div>
<div class="clear"></div>
<?php } ?>

<script type="text/javascript"> 
changeStatus = function(id) {
	$.ajax({
        type: 'post',
        url: "<?php echo $module;?>/orders/change_membership",
        data: 'id=' + id,
        beforeSend: function () {
			$('#'+id).animate({
                'backgroundColor': '#FFBFBF'
            }, 400);
        },
        success: function () {
        	$.get(window.location.href, function(data){
            	var html = $(data).find('#table_change');
            	html.find("#"+id+"").css({'backgroundColor': '#FFBFBF'});
        		$('#table_change').html(html.html());
        		setTimeout(function(){
        			$("#"+id+"").animate({'backgroundColor': 'transparent'}, 400).find('.tooltip').simpletooltip();
        			deleteInit();
        		}, 500);
        	});
        }
	});
};
//]]>
</script>
<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function(){
	var cache = {},
	lastXhr;
	$( ".item_username" ).autocomplete({
		minLength: 2,
		source: function( request, response ) {
			var term = request.term;
			if ( term in cache ) {
				response( cache[ term ] );
				return;
			}
	
			lastXhr = $.getJSON( "<?php echo $module;?>/orders/liveSearch/?filter=user", request, function( data, status, xhr ) {
				cache[ term ] = data;
				if ( xhr === lastXhr ) {
					response( data );
				}
			});
		}
	});
});
//]]>
</script>
<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function(){
	$('#testtt').submit(function(){
		window.location = $('#testtt').joform();
		return false;
	});
});
//]]>
</script>
<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function(){
	deleteInit();
});
//]]>
</script>
<script type="text/javascript"> 
// <![CDATA[
function deleteInit() {
	$('a.delete').click(function (e) {
        if (confirm(lang.confirm)) {
            e.preventDefault();
            var parent = $(this).parents('tr');
            $.ajax({
                type: 'post',
                url: "<?php echo $module;?>/orders/delete_membership",
                data: 'id=' + $(this).attr('id').replace('item_', ''),
                beforeSend: function () {
                    parent.animate({
                        'backgroundColor': '#FFBFBF'
                    }, 400);
                },
                success: function () {
                    parent.fadeOut(400, function () {
                        parent.remove();
                    });
                }
            });
        }
    });
}
// ]]>
</script>