<?php 
	$module = $this->getRequest()->getModule();
?>

<form name="admin_form" id="admin_form" method="post" action="">

	<div class="info_line top">
		<h3 class="fleft title">
			<img alt="" src="cms/<?php echo $module;?>/images/cash.png">
			<?php echo $this->translate('Payments');?> › <?php echo $this->translate('Moneybookers');?>
		</h3>
		
		<span id="fader" class="fleft mleft30" style="display:none;">
			<span class="msgError"><span><?php echo $this->translate('Error');?>!</span><i class="error_text"></i></span>
		</span>
		
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/payments/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>

	<div class="clear"></div>
	
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Status');?>: </td>
				<td>
					<select name="moneybookers[moneybookers_status]">
						<?php if($this->moneybookers_status) { ?>
						<option selected="selected" value="1"><?php echo $this->translate('Enabled');?></option>
						<option value="0"><?php echo $this->translate('Disabled');?></option>
						<?php } else { ?>
						<option value="1"><?php echo $this->translate('Enabled');?></option>
						<option selected="selected" value="0"><?php echo $this->translate('Disabled');?></option>
						<?php } ?>
					</select>
        		</td>
			</tr>
			
			<tr>
				<td><?php echo $this->translate('Secret');?>:</td>
				<td>
					<input type="text" size="60" value="<?php echo $this->moneybookers_secret;?>" class="inputbox"  name="moneybookers[moneybookers_secret]" />
					<br />
					<span class="help">
						<?php echo $this->translate('This secret helps prevent people from being able to bypass the payment and fake the checkout. You get the Secret from your moneybookers account.')?>
					</span>
        		</td>
			</tr>
			
			<tr>
				<td><?php echo $this->translate('E-mail');?>:</td>
				<td>
					<input type="text" size="60" value="<?php echo $this->moneybookers_email;?>" class="inputbox"  name="moneybookers[moneybookers_email]" />
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Sort');?>:</td>
				<td>
					<input type="text" size="60" value="<?php echo $this->moneybookers_sort_order;?>" class="inputbox"  name="moneybookers[moneybookers_sort_order]" />
        		</td>
			</tr>
			
			<tr>
				<td><?php echo $this->translate('Logo');?>:</td>
				<td>
					<input type="hidden" name="moneybookers[moneybookers_logo]" value="<?php echo $this->moneybookers_logo; ?>" id="site_logo" />
					<img id="preview_logo" src="<?php echo $this->preview_logo;?>" />
					<br />
					<a style="cursor: pointer;" onclick="image_upload('site_logo', 'preview_logo');"><?php echo $this->translate('Browse Files'); ?></a>
					&nbsp;&nbsp;|&nbsp;&nbsp;
					<a style="cursor: pointer;" onclick="$('#preview_logo').attr('src', '<?php echo $this->preview; ?>'); $('#site_logo').attr('value', '');"><?php echo $this->translate('Clear Image'); ?></a>
				</td>
			</tr>
			
			
		</tbody>
	</table>
		
	<div class="info_line bottom">
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/payments/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
		
</form>

<script type="text/javascript"><!--
function image_upload(field, preview) {
	$('#dialog').remove();
	
	$('#content').prepend('<div id="dialog" style="padding: 3px 0px 0px 0px;"><iframe src="<?php echo $module;?>/filemanager?field=' + encodeURIComponent(field) + '" style="padding:0; margin: 0; display: block; width: 100%; height: 100%;" frameborder="no" scrolling="auto"></iframe></div>');
	
	$('#dialog').dialog({
		title: '<?php echo $this->translate('File Manager');?>',
		close: function (event, ui) {
			if ($('#' + field).attr('value')) {
				$.ajax({
					url: '<?php echo $module;?>/filemanager/image',
					type: 'POST',
					data: 'image=' + encodeURIComponent($('#' + field).val()),
					dataType: 'text',
					success: function(data) {
						$('#' + preview).attr('src',data);
					}
				});
			}
		},	
		bgiframe: false,
		width: 800,
		height: 400,
		resizable: false,
		modal: false
	});
};
//--></script>