<?php 
	$module = $this->getRequest()->getModule();
?>

<form name="admin_form" id="admin_form" method="post" action="">

	<div class="info_line top">
		<h3 class="fleft title">
			<img alt="" src="cms/<?php echo $module;?>/images/payout.png">
			<?php echo $this->translate('Withdrawals');?>
		</h3>
		
		<span id="fader" class="fleft mleft30" style="display:none;">
			<span class="msgError"><span><?php echo $this->translate('Error!')?></span><i class="error_text"></i></span>
		</span>
		
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/gainpayingup/?page=<?php echo $this->page_num;?>"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>

	<div class="clear"></div>
	
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Username');?>: </td>
				<td>
					<?php echo $this->info['username'];?>
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Payment Method');?>: </td>
				<td>
					<?php echo $this->info['method'];?>
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Text');?>: </td>
				<td>
					<?php echo $this->info['text'];?>
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Australian resident');?>: </td>
				<td>
					<img title="<?php echo ($this->info['australian'] == 'true' ? 'yes' : 'no');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/<?php echo ($this->exclusive_author == 'true' ? 'yes' : 'no');?>.png"> 
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Date');?>: </td>
				<td>
					<?php echo $this->info['datetime'];?>
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Paid');?>: </td>
				<td>
					<img title="<?php echo ($this->info['paid'] == 'true' ? 'yes' : 'no');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/<?php echo ($this->exclusive_author == 'true' ? 'yes' : 'no');?>.png"> 
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Amount');?>: </td>
				<td>
					<?php echo $this->info['amount'];?>
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Currenet ballance');?>: </td>
				<td>
					<?php echo $this->info['earning_formated'];?>
        		</td>
			</tr>
			
			<tr>
				<td><?php echo $this->translate('Pay out');?>: </td>
				<td>
					<input type="text" size="15" value="<?php echo $this->info['amount'];?>" class="inputbox required"  name="earning" />
        		</td>
			</tr>
		</tbody>
	</table>
	
			
		
	<div class="info_line bottom">
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/gainpayingup/?page=<?php echo $this->page_num;?>"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
		
</form>