<?php 
	$module = $this->getRequest()->getModule();
?>
<form name="admin_form" id="admin_form" method="post" action="" enctype="multipart/form-data">

<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/<?php echo $module;?>/images/quiz.png">
		<?php echo $this->translate('Quiz');?> <?php echo ($this->parent_name ? ' › ' . $this->parent_name : '');?>
	</h3>
	
	<span id="fader" class="fleft mleft30" style="display:none;">
		<span class="msgError"><span><?php echo $this->translate('Error!');?></span><i class="error_text"></i></span>
	</span>
	
	<div class="fright mtop3">
		<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
		<a class="button" href="<?php echo $module;?>/quiz/<?php echo ($this->sub_of ? '?sub_of=' . $this->sub_of : '');?>"><?php echo $this->translate('Cancel');?></a>
	</div>
	<div class="clear"></div>
</div>

<div class="clear"></div>

	
	
		<table cellspacing="0" cellpadding="0" class="formtable">
			<tbody>
				<tr>
					<td width="150"><?php echo $this->translate('Name');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
					<td>
						<input type="text" title="<?php echo $this->translate('Please enter a name');?>" size="40" value="<?php echo $this->name;?>" class="inputbox required"  name="name" />
	        		</td>
				</tr>
				<?php if($this->parent_name) { ?>
				<tr>
					<td><?php echo $this->translate('Right');?>: </td>
					<td>
						<input <?php echo ($this->right == 'true' ? 'checked="checked"' : '');?> type="checkbox" name="right" value="true" />
	        		</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
				
		<div class="info_line bottom">
			<div class="fright mtop3">
				<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
				<a class="button" href="<?php echo $module;?>/quiz/<?php echo ($this->sub_of ? '?sub_of=' . $this->sub_of : '');?>"><?php echo $this->translate('Cancel');?></a>
			</div>
			<div class="clear"></div>
		</div>
		
		<div class="clear"></div>
		
	</form>
	