<?php 
	$module = $this->getRequest()->getModule();
?>

<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/<?php echo $module;?>/images/quiz.png">
		<?php echo $this->translate('Quiz');?> <?php echo ($this->parent_name ? ' › ' . $this->parent_name : '');?>
	</h3>
	
	<?php if($this->successfu_edite) { ?>
	<span id="fader" class="fleft mleft30"><span class="msgOk"><span><?php echo $this->translate('Successfully!');?></span><?php echo $this->translate('Information was successfully changed!');?></span></span>
	<script type="text/javascript"> 
	// <![CDATA[
	$(document).ready(function() {       
		setTimeout(function() {
			$("#fader").customFadeOut("slow" ,    
			function() {       
				$("#fader").remove();  
			});
		},
		4000);
	});
	// ]]>
	</script>
	<?php } ?>
	
	<div class="fright mtop3">
		<?php if($this->parent_href) { ?>
		<a class="button" href="<?php echo $this->parent_href;?>"><?php echo $this->translate('Back');?></a>
		<?php } ?>
		<a class="button" href="<?php echo $module;?>/quiz/create/<?php echo ($this->sub_of ? '?sub_of=' . $this->sub_of : '');?>"><?php echo $this->translate(($this->sub_of ? 'Add new answer' : 'Add new quiz'));?></a>
	</div>
	<div class="clear"></div>
</div>


<p class="info">
	<?php echo $this->translate('Attributes Manager');?>.<br>
	<strong><?php echo $this->translate('Note: If you delete an entry, information will be lost.');?></strong>
</p>


<table cellspacing="0" cellpadding="0" class="display dragable_table" id="sort_order">
	<thead>
		<tr class="nodrop nodrag">
			<th width="20" class="left">#</th>
			<th class="left"><?php echo $this->translate('Name');?></th>
			<?php if(!$this->parent_name) { ?>
			<th width="20"><?php echo $this->translate('Answers');?></th>
			<?php } else { ?>
			<th width="20"><?php echo $this->translate('Right');?></th>
			<?php } ?>
			<th width="20"><?php echo $this->translate('Edit');?></th>
			<th width="20"><?php echo $this->translate('Delete');?></th>
		</tr>
	</thead>
	<tbody>
	<?php if($this->pages) { ?>
	<?php foreach($this->pages AS $page) { ?>
		<tr id="<?php echo $page['id'];?>">
			<td><?php echo $page['id'];?>.</td>
			<td><?php echo $page['name'];?></td>
			<?php if(!$this->parent_name) { ?>
			<td align="center">
				<a href="<?php echo $module;?>/quiz/?sub_of=<?php echo $page['id'];?>"><img src="cms/<?php echo $module;?>/images/folder.png" class="tooltip"  alt="" title="<?php echo $this->translate('Answers');?>"/></a>
			</td>
			<?php } else { ?>
			<td align="center">
				<img src="cms/<?php echo $module;?>/images/<?php echo ($page['right'] == 'true' ? 'yes.png' : 'no.png');?>" class="tooltip"  alt="" title="<?php echo ($page['right'] == 'true' ? $this->translate('Yes') : $this->translate('No'));?>" />
			</td>
			<?php } ?>
			<td align="center"><a href="<?php echo $module;?>/quiz/edit/?id=<?php echo $page['id'];?><?php echo ($this->sub_of ? '&sub_of='.$this->sub_of : '');?>"><img title="<?php echo $this->translate('Edit');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/edit.png"></a></td>
			<td align="center">
				<a id="item_<?php echo $page['id'];?>" class="delete" href="javascript:void(0);"><img title="<?php echo $this->translate('Delete');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/delete.png"></a>
			</td>
		</tr>
	<?php } ?>
	<?php } else { ?>
		<tr class="nodrop nodrag">
			<td colspan="5">
				<div class="msgAlert"><span><?php echo $this->translate('Attention!');?></span><?php echo $this->translate('No records found ...');?></div>
			</td>
		</tr>
	<?php } ?>
	</tbody>
</table>


<script type="text/javascript"> 
// <![CDATA[

$(document).ready(function(){
	deleteInit();
	<?php if(!$this->parent_name) { ?>
	dragdropInit();
	<?php } ?>
});

function deleteInit() {
	$('a.delete').click(function (e) {
        if (confirm(lang.confirm)) {
            e.preventDefault();
            var parent = $(this).parents('tr');
            $.ajax({
                type: 'post',
                url: "<?php echo $module;?>/quiz/delete",
                data: 'sub_of=<?php echo $this->sub_of;?>&id=' + $(this).attr('id').replace('item_', ''),
                beforeSend: function () {
                    parent.animate({
                        'backgroundColor': '#FFBFBF'
                    }, 400);
                },
                success: function () {
                    parent.fadeOut(400, function () {
                        parent.remove();
                    });
                }
            });
        }
    });
}

<?php if(!$this->parent_name) { ?>
function dragdropInit() {
	$('.dragable_table').tableDnD({
	    onDrop: function(table, row) {
	        $.post('<?php echo $module;?>/quiz/sort_order/?sub_of=<?php echo $this->sub_of;?>', $.tableDnD.serialize(), function(data){
				if(data) {
					if($("#fader").size()) {
						$("#fader").remove();  
					}
					$('.info_line.top .title').after('<div id="fader" class="fleft mleft30"><div class="msgOk"><span><?php echo $this->translate('Successfully!');?></span><?php echo $this->translate('Information was successfully changed!');?></div></div>');
					setTimeout(function() {
						$("#fader").customFadeOut("slow" ,    
						function() {       
							$("#fader").remove();  
						});
					},
					2000);
				}
		    });
	    }
	});
}
<?php } ?>
// ]]>
</script>