<?php 
	$module = $this->getRequest()->getModule();
?>

<form name="admin_form" id="admin_form" method="post" action="" enctype="multipart/form-data">

	<div class="info_line top">
		<h3 class="fleft title">
			<img alt="" src="cms/<?php echo $module;?>/images/contacts.png">
			<?php echo $this->translate('Contacts Management');?>
		</h3>
		
		<span id="fader" class="fleft mleft30" style="display:none;">
			<span class="msgError"><span><?php echo $this->translate('Error!');?></span><i class="error_text"></i></span>
		</span>
		
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/contacts/?page=<?php echo $this->page_num;?>"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>

	<div class="clear"></div>
	
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Name');?>: </td>
				<td>
					<?php echo $this->info['name'];?>
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('E-mail');?>: </td>
				<td>
					<?php echo $this->info['email'];?>
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Issue');?>: </td>
				<td>
					<?php echo $this->info['issue'];?>
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Text');?>: </td>
				<td>
					<?php echo nl2br($this->info['short_text']);?>
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Answer');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<textarea style="width: 70%;height: 150px;" title="<?php echo $this->translate('Please enter Answer');?>" class="inputbox required"  name="answer"><?php echo $this->answer;?></textarea>
        		</td>
			</tr>
		</tbody>
	</table>
		
	<div class="info_line bottom">
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/contacts/?page=<?php echo $this->page_num;?>"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
		
</form>