<?php 
	$module = $this->getRequest()->getModule();
?>

<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/<?php echo $module;?>/images/contacts.png">
		<?php echo $this->translate('Contacts Management');?>
	</h3>
	
	<?php if($this->successfu_edite) { ?>
	<span id="fader" class="fleft mleft30"><span class="msgOk"><span><?php echo $this->translate('Successfully!');?></span><?php echo $this->translate('Information was successfully changed!');?></span></span>
	<script type="text/javascript"> 
	// <![CDATA[
	$(document).ready(function() {       
		setTimeout(function() {
			$("#fader").customFadeOut("slow" ,    
			function() {       
				$("#fader").remove();  
			});
		},
		4000);
	});
	// ]]>
	</script>
	<?php } ?>
	
	<div class="clear"></div>
</div>


<p class="info">
	<?php echo $this->translate('Management contacts');?><br>
	<strong><?php echo $this->translate('Note: If you delete an entry, information will be lost.');?></strong>
</p>


<table cellspacing="0" cellpadding="0" class="display">
	<thead>
		<tr class="nodrop nodrag">
			<th class="left"><?php echo $this->translate('Name');?></th>
			<th class="left"><?php echo $this->translate('E-mail');?></th>
			<th class="left"><?php echo $this->translate('Issue');?></th>
			<th class="left"><?php echo $this->translate('Date');?></th>
			<th class="left"><?php echo $this->translate('Answer Date');?></th>
			<th width="50"><?php echo $this->translate('Has response');?></th>
			<th width="50"><?php echo $this->translate('View');?></th>
			<th width="50"><?php echo $this->translate('Delete');?></th>
		</tr>
	</thead>
	<tbody>
	<?php if($this->contacts) { ?>
	<?php foreach($this->contacts AS $contact) { ?>
		<tr>
			<td><?php echo $contact['name'];?></td>
			<td><?php echo $contact['email'];?></td>
			<td><?php echo $contact['issue'];?></td>
			<td><?php echo $contact['datetime'];?></td>
			<td><?php echo $contact['answer_datetime'];?></td>
			<td align="center"><img title="<?php echo ($contact['has_response'] ? $this->translate('Yes') : $this->translate('No'));?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/<?php echo ($contact['has_response'] ? 'yes' : 'no');?>.png"></td>
			<td align="center"><a href="<?php echo $module;?>/contacts/edit/?id=<?php echo $contact['id'];?>&page=<?php echo $this->page_num;?>"><img title="<?php echo $this->translate('View');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/view.png"></a></td>
			<td align="center"><a id="item_<?php echo $contact['id'];?>" class="delete" href="javascript:void(0);"><img title="<?php echo $this->translate('Delete');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/delete.png"></a></td>
		</tr>
	<?php } ?>
	<?php } else { ?>
		<tr class="nodrop nodrag">
			<td colspan="8">
				<div class="msgAlert"><span><?php echo $this->translate('Attention!');?></span><?php echo $this->translate('No records found ...');?></div>
			</td>
		</tr>
	<?php } ?>
	</tbody>
</table>

<?php if($this->pagination) { ?>
<br />
<div class="fleft">
<?php echo $this->translate('Page');?> <b><?php echo $this->page_num;?></b> <?php echo $this->translate('from');?> <b><?php echo $this->total_pages;?></b> (<b><?php echo $this->total_rows;?></b> <?php echo $this->translate('records');?>)
</div>
<div class="pagination fright">
	<?php echo $this->pagination;?>
</div>
<div class="clear"></div>
<?php } ?>

<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function(){
	$('a.delete').click(function (e) {
        if (confirm(lang.confirm)) {
            e.preventDefault();
            var parent = $(this).parents('tr');
            $.ajax({
                type: 'post',
                url: "<?php echo $module;?>/contacts/delete",
                data: 'id=' + $(this).attr('id').replace('item_', ''),
                beforeSend: function () {
                    parent.animate({
                        'backgroundColor': '#FFBFBF'
                    }, 400);
                },
                success: function () {
                    parent.fadeOut(400, function () {
                        parent.remove();
                    });
                }
            });
        }
    });
});

// ]]>
</script>