<?php 
	$module = $this->getRequest()->getModule();
?>

<form name="admin_form" id="admin_form" method="post" action="">

	<div class="info_line top">
		<h3 class="fleft title">
			<img alt="" src="cms/<?php echo $module;?>/images/items.png">
			<?php echo $this->translate('Items');?>
		</h3>
		
		<span id="fader" class="fleft mleft30" style="display:none;">
			<span class="msgError"><span><?php echo $this->translate('Error!')?></span><i class="error_text"></i></span>
		</span>
		
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<input type="submit" value="<?php echo $this->translate('Delete');?>" class="button" name="delete">
			<a class="button" href="<?php echo $this->cancel;?>"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>

	<div class="clear"></div>
	
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Username');?>: </td>
				<td>
					<?php echo $this->info['username'];?>
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Name');?>: </td>
				<td>
					<?php echo $this->info['name'];?>
        		</td>
			</tr>
			<?php if($this->info['reviewer_comment']) { ?>
			<tr>
				<td><?php echo $this->translate('Reviewer comment');?>: </td>
				<td>
					<?php echo nl2br($this->info['reviewer_comment']);?>
        		</td>
			</tr>
			<?php } ?>
			<tr>
				<td><?php echo $this->translate('Thumb');?>: </td>
				<td>
					<img src="<?php echo $this->info['thumbnail'];?>" alt="" />
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Preview');?>: </td>
				<td>
					<img src="<?php echo $this->info['theme_preview_thumbnail'];?>" alt="" />
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Theme Preview');?>: </td>
				<td>
					<a href="uploads/<?php echo $this->info['theme_preview'];?>"><?php echo $this->info['theme_preview'];?></a>
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Main Files(s)');?>: </td>
				<td>
					<a href="uploads/<?php echo $this->info['main_file'];?>"><?php echo $this->info['main_file'];?></a>
        		</td>
			</tr>
			
			
		</tbody>
	</table>

	<br /><br />
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Name');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" title="<?php echo $this->translate('Please enter a name');?>" size="55" value="<?php echo $this->name;?>" class="inputbox required"  name="name" />
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Description');?>: </td>
				<td>
					<textarea rows="4" cols="53" name="description" class="valid ckeditor_replace"><?php echo $this->description;?></textarea>
        		</td>
			</tr>
		</tbody>
	</table>
	<br /><br />
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Category');?>:</td>
				<td>
					<div class="scrollbox category-list">
						<?php if($this->categories) { ?>
						<?php $i = 0; ?>
						<?php foreach($this->categories AS $key => $records_type) { ?>
							<?php if(substr_count($records_type['name'], '>>') > 1) continue; ?>
						<div class="<?php echo ($i%2 ? 'odd' : 'even');?>">
							<?php if(in_array($records_type['id'], $this->category_id)) { ?>
							<input class="record_type required" type="checkbox" checked="checked" value="<?php echo $records_type['id'];?>" name="category_id[]"> <?php echo $records_type['name'];?>
							<?php } else { ?>
							<input class="record_type required" type="checkbox" value="<?php echo $records_type['id'];?>" name="category_id[]"> <?php echo $records_type['name'];?>
							<?php } ?>
						</div>
						<?php $i++; ?>
						<?php } ?>
						<?php } ?>   
					</div>
					<br />
					<label style="position:static;margin-left:0;display:none;" for="category_id[]" class="error"><?php echo $this->translate('Please select a category or categories!');?></label>
        		</td>
			</tr>
		</tbody>
	</table>
	<br /><br />
	<?php if($this->attributes_list) { ?>
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<?php foreach($this->attributes_list AS $attr) { ?>			
			<tr>
				<td width="150"><?php echo $attr['name'];?>:</td>
				<td>
					<?php if($attr['type'] == 'select') { ?>
					<select name="attributes[<?php echo $attr['id'];?>]" class="inputbox">
						<option value=""></option>
						<?php foreach($attr['items'] AS $item) { ?>
						<?php if(isset($this->attributes[$attr['id']]) && $this->attributes[$attr['id']] == $item['id']) { ?>
						<option selected="selected" value="<?php echo $item['id'];?>"><?php echo $item['name'];?></option>
						<?php } else { ?>
						<option value="<?php echo $item['id'];?>"><?php echo $item['name'];?></option>
						<?php } ?>
						<?php } ?>
					</select>
					<?php } elseif($attr['type'] == 'check') { ?>
						<?php foreach($attr['items'] AS $item) { ?>
						<div>
							<label for="i_<?php echo $item['id'];?>">
								<?php if(isset($this->attributes[$attr['id']]) && is_array($this->attributes[$attr['id']]) && in_array($item['id'], $this->attributes[$attr['id']])) { ?>
								<input checked="checked" id="i_<?php echo $item['id'];?>" type="checkbox" name="attributes[<?php echo $attr['id'];?>][<?php echo $item['id'];?>]" value="<?php echo $item['id'];?>" /> <?php echo $item['name'];?>
								<?php } else { ?>
								<input id="i_<?php echo $item['id'];?>" type="checkbox" name="attributes[<?php echo $attr['id'];?>][]" value="<?php echo $item['id'];?>" /> <?php echo $item['name'];?>
								<?php } ?>
							</label>
						</div>
						<?php } ?>
					<?php } elseif($attr['type'] == 'radio') { ?>
						<?php foreach($attr['items'] AS $item) { ?>
						<div>
							<label for="i_<?php echo $item['id'];?>">
								<?php if(isset($this->attributes[$attr['id']]) && $this->attributes[$attr['id']] == $item['id']) { ?>
								<input checked="checked" id="i_<?php echo $item['id'];?>" type="radio" name="attributes[<?php echo $attr['id'];?>]" value="<?php echo $item['id'];?>" /> <?php echo $item['name'];?>
								<?php } else { ?>
								<input id="i_<?php echo $item['id'];?>" type="radio" name="attributes[<?php echo $attr['id'];?>]" value="<?php echo $item['id'];?>" /> <?php echo $item['name'];?>
								<?php } ?>
							</label>
						</div>
						<?php } ?>
					<?php } elseif($attr['type'] == 'input') { ?>
					<input type="text" class="inputbox" name="attributes[<?php echo $attr['id'];?>]" value="<?php echo ( isset($this->attributes[$attr['id']]) ? $this->attributes[$attr['id']] : '' );?>" />
					<?php } ?>
        		</td>
			</tr>
			<?php } ?>
		</tbody>
	</table>
	<br /><br />
	<?php } ?>
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Tags');?>:</td>
				<td>
					<input type="text" size="55" value="<?php echo $this->tags;?>" class="inputbox tagInput"  name="tags" />
        		</td>
			</tr>
		</tbody>
	</table>
	<br /><br />
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Demo URL');?>:</td>
				<td>
					<input type="text" size="55" value="<?php echo $this->demo_url;?>" class="inputbox"  name="demo_url" />
        		</td>
			</tr>
		</tbody>
	</table>
	<br /><br />
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Weekly features from');?>:</td>
				<td>
					<input type="text" size="55" value="<?php echo $this->weekly_from;?>" class="inputbox datepicer"  name="weekly_from" />
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Weekly features to');?>:</td>
				<td>
					<input type="text" size="55" value="<?php echo $this->weekly_to;?>" class="inputbox datepicer"  name="weekly_to" />
        		</td>
			</tr>
		</tbody>
	</table>
	<br /><br />
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<?php if($this->info['free_request'] == 'true') { ?>
			<tr>
				<td><?php echo $this->translate('Free request');?>: </td>
				<td>
					<img title="<?php echo ($this->info['free_request'] == 'true' ? $this->translate('Yes') : $this->translate('No'));?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/<?php echo ($this->info['free_request'] == 'true' ? 'yes' : 'no');?>.png"> 
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Free file');?>: </td>
				<td>
					<input type="checkbox" value="true" <?php echo ($this->free_file == 'true' ? 'checked="checked"' : '');?> class="inputbox free_file_select"  name="free_file" />
        		</td>
			</tr>
			<?php } ?>
			<tr>
				<td width="150"><?php echo $this->translate('Suggested price from user');?>: </td>
				<td style="font-weight: bold;">
					<?php echo $this->price_f;?>
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Price');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" size="55" value="<?php echo $this->price;?>"  class="inputbox required"  name="price" />
        		</td>
			</tr>
		</tbody>
	</table>
	<br /><br />
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Delete message');?>:</td>
				<td>
					<textarea rows="4" cols="53" name="message" class="valid"></textarea>
        		</td>
			</tr>
		</tbody>
	</table>
		
	<div class="info_line bottom">
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<input type="submit" value="<?php echo $this->translate('Delete');?>" class="button" name="delete">
			<a class="button" href="<?php echo $this->cancel;?>"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
		
</form>

<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function(){
	$( ".datepicer" ).datepicker({
		dateFormat : 'dd.mm.yy'
	});
});
//]]>
</script>

<script type="text/javascript">
function split( val ) {
	return val.split( /,\s*/ );
}
function extractLast( term ) {
	return split( term ).pop();
}

$(document).ready(function() {
	$(".tagInput").bind( "keydown", function( event ) {
		if ( event.keyCode === $.ui.keyCode.TAB &&
				$( this ).data( "autocomplete" ).menu.active ) {
				event.preventDefault();
		}
	}).autocomplete({
		source: function( request, response ) {
			$.getJSON( '<?php echo $module;?>/items/liveSearch/?filter=tags', {
				term: extractLast( request.term )
			}, response );
		},
		multiple: true,
		matchContains: true,
		select: function( event, ui ) {
			var terms = split( this.value );
			terms.pop();
			terms.push( ui.item.value );
			terms.push( "" );
			this.value = terms.join( "," );
			return false;
		},
		focus: function() {
			// prevent value inserted on focus
			return false;
		}
	});			
});
</script>