<?php 
	$module = $this->getRequest()->getModule();
?>

<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/<?php echo $module;?>/images/items.png">
		<?php echo $this->translate('Items');?>
	</h3>
	
	<?php if($this->successfu_edite) { ?>
	<span id="fader" class="fleft mleft30"><span class="msgOk"><span><?php echo $this->translate('Successfully!');?></span><?php echo $this->translate('Information was successfully changed!');?></span></span>
	<script type="text/javascript"> 
	// <![CDATA[
	$(document).ready(function() {       
		setTimeout(function() {
			$("#fader").customFadeOut("slow" ,    
			function() {       
				$("#fader").remove();  
			});
		},
		4000);
	});
	// ]]>
	</script>
	<?php } ?>
	
	<div class="fright mtop3">
		<a class="button" href="javascript:void(0);" onclick="multiActionSelected('deleteMulti');"><?php echo $this->translate('Delete selected');?></a>
	</div>
	<div class="clear"></div>
</div>


<p class="info">
	<?php echo $this->translate('Items Manager');?>.<br>
	<strong><?php echo $this->translate('Note: If you delete an entry, information will be lost.');?></strong>
</p>

<form action="<?php echo $module;?>/items/" method="get" id="testtt">
<table cellspacing="0" cellpadding="0" class="display" id="table_change">
	<thead>
		<tr>
			<th width="20">
				<input type="checkbox" class="check_all_list" />
			</th>
			<th width="20" class="left">
				<a href="<?php echo $this->sort_id;?>" <?php if($this->order == 'i.id') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>>#</a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_name;?>" <?php if($this->order == 'i.name') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Name');?></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_username;?>" <?php if($this->order == 'u.username') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Seller');?></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_price;?>" <?php if($this->order == 'i.price') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Price');?></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_sales;?>" <?php if($this->order == 'i.sales') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Sales');?></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_earning;?>" <?php if($this->order == 'i.earning') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Seller Profit');?></a>
			</th>
			
			<th class="left">
				<a href="<?php echo $this->sort_web_profit;?>" <?php if($this->order == 'web_profit2') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Website Profit');?></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_referral_sum;?>" <?php if($this->order == 'referral_sum') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Refferals');?></a>
			</th>
			
			<th class="left">
				<a href="<?php echo $this->sort_free_request;?>" <?php if($this->order == 'i.free_request') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Free request');?></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_free_file;?>" <?php if($this->order == 'i.free_file') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Free file');?></a>
			</th>
			<th class="left"><?php echo $this->translate('Weekly features');?></th>
			<th width="20"><?php echo $this->translate('Comments');?></th>
			<th width="20"><?php echo $this->translate('Edit');?></th>
			<th width="20"><?php echo $this->translate('Delete');?></th>
		</tr>
		<tr class="search">
			<th class="left" colspan="2">
				<input class="inputbox" type="text" name="filter_id" value="<?php echo $this->filter_id;?>" size="4" />
			</th>
			<th class="left">
				<input class="inputbox item_title" type="text" name="filter_name" value="<?php echo $this->filter_name;?>" size="30" />
			</th>
			<th class="left">
				<input class="inputbox item_username" type="text" name="filter_username" value="<?php echo $this->filter_username;?>" size="8" />
			</th>
			<th class="left">
				<input class="inputbox" type="text" name="filter_price" value="<?php echo $this->filter_price;?>" size="5" />
			</th>
			<th class="left">
				<input class="inputbox" type="text" name="filter_sales" value="<?php echo $this->filter_sales;?>" size="3" />
			</th>
			<th class="left">
				<input class="inputbox" type="text" name="filter_profit" value="<?php echo $this->filter_profit;?>" size="5" />
			</th>
			
			<th class="left">
				<input class="inputbox" type="text" name="filter_web_profit" value="<?php echo $this->filter_web_profit;?>" size="5" />
			</th>
			<th class="left">
				<input class="inputbox" type="text" name="filter_refferals" value="<?php echo $this->filter_refferals;?>" size="5" />
			</th>
			
			<th class="left">
				<select name="filter_free_request" class="inputbox" style="width: 60px;">
					<?php if($this->filter_free_request == 'true') { ?>
					<option value=""></option>
					<option selected="selected" value="true"><?php echo $this->translate('Yes');?></option>
					<option value="false"><?php echo $this->translate('No');?></option>
					<?php } elseif($this->filter_free_request == 'false') { ?>
					<option value=""></option>
					<option value="true"><?php echo $this->translate('Yes');?></option>
					<option selected="selected" value="false"><?php echo $this->translate('No');?></option>
					<?php } else { ?>
					<option value=""></option>
					<option value="true"><?php echo $this->translate('Yes');?></option>
					<option value="false"><?php echo $this->translate('No');?></option>
					<?php } ?>
				</select>
			</th>
			<th class="left">
				<select name="filter_free_file" class="inputbox" style="width: 60px;">
					<?php if($this->filter_free_file == 'true') { ?>
					<option value=""></option>
					<option selected="selected" value="true"><?php echo $this->translate('Yes');?></option>
					<option value="false"><?php echo $this->translate('No');?></option>
					<?php } elseif($this->filter_free_file == 'false') { ?>
					<option value=""></option>
					<option value="true"><?php echo $this->translate('Yes');?></option>
					<option selected="selected" value="false"><?php echo $this->translate('No');?></option>
					<?php } else { ?>
					<option value=""></option>
					<option value="true"><?php echo $this->translate('Yes');?></option>
					<option value="false"><?php echo $this->translate('No');?></option>
					<?php } ?>
				</select>
			</th>
			<th class="left">
				<input class="inputbox datepicer" type="text" name="filter_weekly" value="<?php echo $this->filter_weekly;?>" size="10" />
			</th>
			<th colspan="3">
					<input type="submit" value="<?php echo $this->translate('Filter');?>" class="button">
					&nbsp; <a href="<?php echo $module;?>/items/"><img src="cms/<?php echo $module;?>/images/reload.png" class="tooltip"  alt="" title="<?php echo $this->translate('Reset');?>" /></a>
			</th>
		</tr>
	</thead>
	<tbody>
	<?php if($this->items) { ?>
	<?php foreach($this->items AS $item) { ?>
		<tr id="<?php echo $item['id'];?>">
			<td>
				<input type="checkbox" class="check_list" name="action_check[]" value="<?php echo $item['id'];?>" />
			</td>
			<td><?php echo $item['id'];?>.</td>
			<td>
				<a href="<?php echo $item['href'];?>" target="_blank">
					<?php echo $item['name'];?>
				</a>
			</td>
			<td>
				<a href="<?php echo $module;?>/items/?filter_user_id=<?php echo $item['user_id'];?>">
					<?php echo $item['username'];?>
				</a>
			</td>
			<td><?php echo $item['price'];?></td>
			<td align="center"><?php echo $item['sales'];?></td>
			<td><?php echo $item['receive'];?></td>
			
			<td>
				<?php if($item['has_referral_sum']) { ?>
					<a class="tooltip" title="<?php echo $this->translate('Website receive');?> <?php echo $item['web_profit'];?> - <?php echo $this->translate('Seller referral receive');?> <?php echo $item['referral_sum'];?> = <?php echo $item['web_profit2'];?>"><?php echo $item['web_profit2'];?></a>
				<?php } else { ?>
					<?php echo $item['web_profit2'];?>
				<?php } ?>
			</td>
			<td><?php echo $item['referral_sum'];?></td>
			
			<td align="center"><img src="cms/<?php echo $module;?>/images/<?php echo ($item['free_request'] ? 'yes.png' : 'no.png');?>" class="tooltip"  alt="" title="<?php echo ($item['free_request'] ? $this->translate('Yes') : $this->translate('No'));?>" /></td>
			<td align="center">
				<?php if($item['free_request']) { ?>
					<a href="javascript:void(0);" onclick="changeStatus(<?php echo $item['id'];?>);">
						<img src="cms/<?php echo $module;?>/images/<?php echo ($item['free_file'] ? 'yes.png' : 'no.png');?>" class="tooltip"  alt="" title="<?php echo ($item['free_file'] ? $this->translate('Yes') : $this->translate('No'));?>" />
					</a>
				<?php } else {  ?>
					<img src="cms/<?php echo $module;?>/images/<?php echo ($item['free_file'] ? 'yes.png' : 'no.png');?>" class="tooltip"  alt="" title="<?php echo ($item['free_file'] ? $this->translate('Yes') : $this->translate('No'));?>" />
				<?php } ?>
			</td>
			<td align="center"><?php echo $item['weekly_from'];?> - <?php echo $item['weekly_to'];?></td>

			<td align="center"><a href="<?php echo $item['comments_href'];?>"><img title="<?php echo $this->translate('Comments');?> (<?php echo $item['comments'];?>)" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/comments2.png"> (<?php echo $item['comments'];?>)</a></td>
			
			<td align="center"><a href="<?php echo $item['edit'];?>"><img title="<?php echo $this->translate('Edit');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/edit.png"></a></td>
			<td align="center">
				<a id="item_<?php echo $item['id'];?>" class="delete" href="javascript:void(0);"><img title="<?php echo $this->translate('Delete');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/delete.png"></a>
			</td>
		</tr>
	<?php } ?>
	<?php } else { ?>
		<tr>
			<td colspan="15">
				<div class="msgAlert"><span><?php echo $this->translate('Attention!');?></span><?php echo $this->translate('No records found ...');?></div>
			</td>
		</tr>
	<?php } ?>
	</tbody>
</table>
</form>
<?php if($this->pagination) { ?>
<br />
<div class="fleft">
<?php echo $this->translate('Page');?> <b><?php echo $this->page_num;?></b> <?php echo $this->translate('from');?> <b><?php echo $this->total_pages;?></b> (<b><?php echo $this->total_rows;?></b> <?php echo $this->translate('records');?>)
</div>
<div class="pagination fright">
	<?php echo $this->pagination;?>
</div>
<div class="clear"></div>
<?php } ?>

<script type="text/javascript"> 
changeStatus = function(id) {
	$.ajax({
        type: 'post',
        url: "<?php echo $module;?>/items/changeStatus",
        data: 'id=' + id,
        beforeSend: function () {
			$('#'+id).animate({
                'backgroundColor': '#FFBFBF'
            }, 400);
        },
        success: function () {
        	$.get(window.location.href, function(data){
            	var html = $(data).find('#table_change');
            	html.find("#"+id+"").css({'backgroundColor': '#FFBFBF'});
        		$('#table_change').html(html.html());
        		setTimeout(function(){
        			$("#"+id+"").animate({'backgroundColor': 'transparent'}, 400).find('.tooltip').simpletooltip();
        			deleteInit();
        		}, 500);
        	});
        }
	});
};
//]]>
</script>
<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function(){
	var cache = {},
	lastXhr;
	$( ".item_title" ).autocomplete({
		minLength: 2,
		source: function( request, response ) {
			var term = request.term;
			if ( term in cache ) {
				response( cache[ term ] );
				return;
			}
	
			lastXhr = $.getJSON( "<?php echo $module;?>/items/liveSearch/?filter=item", request, function( data, status, xhr ) {
				cache[ term ] = data;
				if ( xhr === lastXhr ) {
					response( data );
				}
			});
		}
	});
});
//]]>
</script>
<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function(){
	var cache = {},
	lastXhr;
	$( ".item_username" ).autocomplete({
		minLength: 2,
		source: function( request, response ) {
			var term = request.term;
			if ( term in cache ) {
				response( cache[ term ] );
				return;
			}
	
			lastXhr = $.getJSON( "<?php echo $module;?>/items/liveSearch/?filter=user", request, function( data, status, xhr ) {
				cache[ term ] = data;
				if ( xhr === lastXhr ) {
					response( data );
				}
			});
		}
	});
});
//]]>
</script>
<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function(){
	$( ".datepicer" ).datepicker({
		dateFormat : 'dd.mm.yy'
	});
});
//]]>
</script>
<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function(){
	$('#testtt').submit(function(){
		window.location = $('#testtt').joform();
		return false;
	});
});
//]]>
</script>
<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function(){
	deleteInit();
});
//]]>
</script>
<script type="text/javascript"> 
// <![CDATA[
function deleteInit() {
	$('a.delete').click(function (e) {
        if (confirm(lang.confirm)) {
            e.preventDefault();
            var parent = $(this).parents('tr');
            $.ajax({
                type: 'post',
                url: "<?php echo $module;?>/items/delete",
                data: 'id=' + $(this).attr('id').replace('item_', ''),
                beforeSend: function () {
                    parent.animate({
                        'backgroundColor': '#FFBFBF'
                    }, 400);
                },
                success: function () {
                    parent.fadeOut(400, function () {
                        parent.remove();
                    });
                }
            });
        }
    });
}
// ]]>
</script>