<?php echo $this->header_part; ?>

<div id="content">
	<div class="breadcrumb">
		<p><?php
			$output = array();
			foreach($this->crumbs as $crumb) {
				if(isset($crumb['href']))
					$output[] = '<a href="'. $crumb['href'] .'">'. $crumb['name'] .'</a>';
				else
					$output[] = $crumb['name'];
			}
			
			echo implode(' &nbsp;&rsaquo;&nbsp; ', $output);
		?></p>
	</div>
	<?php echo $this->author_header; ?>
	<?php if($this->items) { ?>
	<div class="options">	
		<div class="sort">
			<p><span class="label"><?php echo $this->translate('Sorted by')?>:</span> <a href="<?php echo $this->orders[0]['href']; ?>" class="up<?php echo $this->orders[0]['is_selected'] ? ' active' : ''; ?>"><?php echo $this->orders[0]['name']; ?></a> <a href="<?php echo $this->orders[1]['href']; ?>" class="down<?php echo $this->orders[1]['is_selected'] ? ' active' : ''; ?>"><?php echo $this->orders[1]['name']; ?></a> 
			<?php foreach($this->sort_by as $sort) { ?>
			<a href="<?php echo $sort['href']; ?>"<?php echo $sort['is_selected'] ? ' class="active"' : ''; ?>><?php echo $sort['name']; ?></a> 
			<?php } ?>
			<?php if($this->my_profile) { ?>
			<span class="c_type"><a href="<?php echo $this->public_href; ?>"<?php echo $this->public ? ' class="active"' : ''; ?>><?php echo $this->translate('public'); ?></a> <a href="<?php echo $this->private_href; ?>"<?php echo $this->public ? '' : ' class="active"'; ?>><?php echo $this->translate('private'); ?></a></span>
			<?php } ?></p>
			<div class="clear"></div>
		</div>
		<?php if($this->pagination) { ?>
		<div class="pagination">
			<p><?php echo $this->pagination; ?></p>
		</div>
		<?php } ?>
		<?php if($this->my_profile) { ?>
		<div class="filter newcollection">
			<ul>
				<li class="last" id="fm_collection">
					<a href="#" class="btn" id="btn_collection"><span class="arrow"><?php echo $this->form_name; ?></span></a>
					<div class="dropdown right" id="collection_form">
						<div class="columns">
							<form action="<?php echo $this->upload_link; ?>" method="post" class="dropform" enctype="multipart/form-data">
								<p>
									<label for="col-1" class="hide"><?php echo $this->translate('Title'); ?><br /></label>
									<input type="text" name="name" id="col-1" value="<?php echo $this->translate('Title'); ?>" />
								</p>
								<p>
									<label for="col-2" class="hide"><?php echo $this->translate('Description'); ?><br /></label>
									<textarea id="col-2" name="description" cols="50" rows="5"><?php echo $this->translate('Description'); ?></textarea>
								</p>
								<p class="upload">
									<span class="thumb"><?php echo $this->translate('Add cover image'); ?></span>
									<a href="#" class="button-silver" onclick="javascript:$('#file_upload').trigger('click'); return false;">Browse</a>
									<input type="file" name="file_upload" id="file_upload" value="" />
									<br class="clear" />
								</p>
								<p>
									<input type="checkbox" id="col-3" name="publically_visible" /><label for="col-3"><?php echo $this->translate('Make Public'); ?></label>
								</p>
								<p class="submit"><input type="submit" value="<?php echo $this->translate('Save Changes'); ?>" /></p>
							</form>
						</div>
					</div>
				</li>
			</ul>
			<div class="clear"></div>
		</div>
		<?php } ?>
		<div class="clear"></div>
	</div>
	<?php if(isset($this->msg_success)) { ?>
	<p id="msg" class="msg box-success"><?php echo $this->msg_success; ?></p>
	<?php } ?>
	<?php if(isset($this->msg_error)) { ?>
	<p id="msg" class="msg box-error"><?php echo $this->msg_error; ?></p>
	<?php } ?>
	<div class="templates">
		<?php foreach($this->items as $item) { ?>
		<?php echo $item; ?>
		<?php } ?>
	</div>
	<div class="pagination bottom">
		<p><?php echo $this->pagination; ?></p>
	</div>
	<?php } else { 
		if($this->my_profile) { ?>
	<div class="options">
		<div class="sort">
			<p><span class="c_type mr"><a href="<?php echo $this->public_href; ?>"<?php echo $this->public ? ' class="active"' : ''; ?>><?php echo $this->translate('public'); ?></a> <a href="<?php echo $this->private_href; ?>"<?php echo $this->public ? '' : ' class="active"'; ?>><?php echo $this->translate('private'); ?></a></span></p>
		</div>	
		<div class="filter newcollection">
			<ul style="margin-left: 17px;">
				<li class="last" id="fm_collection">
					<a href="#" class="btn" id="btn_collection"><span class="arrow"><?php echo $this->form_name; ?></span></a>
					<div class="dropdown right" id="collection_form">
						<div class="columns">
							<form action="<?php echo $this->upload_link; ?>" method="post" class="dropform" enctype="multipart/form-data">
								<p>
									<label for="col-1" class="hide"><?php echo $this->translate('Title'); ?><br /></label>
									<input type="text" name="name" id="col-1" value="<?php echo $this->translate('Title'); ?>" />
								</p>
								<p>
									<label for="col-2" class="hide"><?php echo $this->translate('Description'); ?><br /></label>
									<textarea id="col-2" name="description" cols="50" rows="5"><?php echo $this->translate('Description'); ?></textarea>
								</p>
								<p class="upload">
									<span class="thumb"><?php echo $this->translate('Add cover image'); ?></span>
									<a href="#" class="button-silver" onclick="javascript:$('#file_upload').trigger('click'); void(0); return false;">Browse</a>
									<input type="file" name="file_upload" id="file_upload" value="" />
									<br class="clear" />
								</p>
								<p>
									<input type="checkbox" id="col-3" name="publically_visible" /><label for="col-3"><?php echo $this->translate('Make Public'); ?></label>
								</p>
								<p class="submit"><input type="submit" value="<?php echo $this->translate('Save Changes'); ?>" /></p>
							</form>
						</div>
					</div>
				</li>
			</ul>
			<div class="clear"></div>
		</div>
		<div class="clear"></div>
	</div>
	<?php } ?>
	<div class="viewall"><p><?php echo $this->translate('No collections yet'); ?></p></div>
	<?php } ?>
	<div class="clear"></div>
</div>
 	
<?php echo $this->footer_part;?>