<?php echo $this->header_part; ?>


<div id="content">
	<div class="breadcrumb">
		<p><?php
			$output = array();
			foreach($this->crumbs as $crumb) {
				if(isset($crumb['href']))
					$output[] = '<a href="'. $crumb['href'] .'">'. $crumb['name'] .'</a>';
				else
					$output[] = $crumb['name'];
			}
			
			echo implode(' &nbsp;&rsaquo;&nbsp; ', $output);
		?></p>
	</div>
	<?php echo $this->author_header; ?>
	<?php if($this->orders) { ?>
	<?php if(isset($this->msg_success)) { ?>
	<p id="msg" class="msg box-success mgnt20px1"><?php echo $this->msg_success; ?></p>
	<?php } ?>
	<?php if(isset($this->msg_error)) { ?>
	<p id="msg" class="msg box-error mgnt20px1"><?php echo $this->msg_error; ?></p>
	<?php } ?>
	<div class="templates">
		<?php foreach($this->orders as $order) { ?>
		<?php echo $order; ?>
		<?php } ?>
	</div>
	<?php } else { ?>
	<div class="viewall"><p><?php echo $this->translate('No downloads yet'); ?></p></div>
	<?php } ?>
	<div class="clear"></div>
</div>

<?php echo $this->footer_part; ?>