<?php echo $this->header_part; ?>

<div id="content">
	<div class="breadcrumb">
		<p><?php
			$output = array();
			foreach($this->crumbs as $crumb) {
				if(isset($crumb['href']))
					$output[] = '<a href="'. $crumb['href'] .'">'. $crumb['name'] .'</a>';
				else
					$output[] = $crumb['name'];
			}
			
			echo implode(' &nbsp;&rsaquo;&nbsp; ', $output);
		?></p>
	</div>
	<?php echo $this->author_header; ?>
	<?php echo $this->author_form; ?>
	<div class="clear"></div>
</div>

<?php echo $this->footer_part; ?>