<?php echo $this->header_part; ?>

<div id="content">
	<div class="breadcrumb">
		<p><?php
			$output = array();
			foreach($this->crumbs as $crumb) {
				if(isset($crumb['href']))
					$output[] = '<a href="'. $crumb['href'] .'">'. $crumb['name'] .'</a>';
				else
					$output[] = $crumb['name'];
			}
			
			echo implode(' &nbsp;&rsaquo;&nbsp; ', $output);
		?></p>
	</div>
	<?php echo $this->author_header; ?>
	<?php if($this->items) { ?>
	<div class="options">	
		<div class="sort">
			<p><span class="label"><?php echo $this->translate('Sorted by')?>:</span> <a href="<?php echo $this->orders[0]['href']; ?>" class="up<?php echo $this->orders[0]['is_selected'] ? ' active' : ''; ?>"><?php echo $this->orders[0]['name']; ?></a> <a href="<?php echo $this->orders[1]['href']; ?>" class="down<?php echo $this->orders[1]['is_selected'] ? ' active' : ''; ?>"><?php echo $this->orders[1]['name']; ?></a> 
			<?php foreach($this->sort_by as $sort) { ?>
			<a href="<?php echo $sort['href']; ?>"<?php echo $sort['is_selected'] ? ' class="active"' : ''; ?>><?php echo $sort['name']; ?></a> 
			<?php } ?></p>
			<div class="clear"></div>
		</div>
		<div class="pagination">
			<p><?php echo $this->pagination; ?></p>
		</div>
		<div class="clear"></div>
	</div>
	<?php if(isset($this->msg_success)) { ?>
	<p id="msg" class="msg box-success"><?php echo $this->msg_success; ?></p>
	<?php } ?>
	<div class="templates">
		<?php foreach($this->items as $item) { ?>
		<?php echo $item; ?>
		<?php } ?>
	</div>
	<div class="pagination bottom">
		<p><?php echo $this->pagination; ?></p>
	</div>
	<?php } else { ?>
	<div class="viewall"><p><?php echo $this->translate('No items yet'); ?></p></div>
	<?php } ?>
	<div class="clear"></div>
</div>
 	
<?php echo $this->footer_part;?>