<?php echo $this->header_part; ?>

<div id="content">
	<div class="breadcrumb">
		<p><a href="<?php echo $this->getRequest()->getBaseUrl(); ?>"><?php echo $this->translate('Home'); ?></a> &nbsp;&rsaquo;&nbsp; <?php echo $this->translate('Login'); ?></p>
	</div>
	<div id="main" class="withhead">
		<div class="textboard">
			<h3 class="ntm"><?php echo $this->translate('Login'); ?></h3>
		</div>
		<form action="" method="post" style="padding-top: 15px;" class="form">
			<?php if(isset($this->check_error)) { ?>
			<p class="checkerror box-error"><?php echo $this->check_error; ?></p>
			<?php } ?>
			<p class="input">
				<label for="f1" class="label"><?php echo $this->translate('Username'); ?> *<br class="hide" /></label>
				<input type="text" name="username" id="f1" value="<?php echo $this->user['username'];?>" />				
			</p>
			<p class="input">
				<label for="f2" class="label"><?php echo $this->translate('Password'); ?> *<br class="hide" /></label>
				<input type="password" name="password" id="f2" value="<?php echo $this->user['password'];?>" />
			</p>
			<p class="submit">
				<input type="submit" name="login" value="<?php echo $this->translate('Login'); ?>" />
				<a href="<?php echo $this->facebook_link; ?>" style="float: left;margin-left:10px"><img src="data/themes/images/facebook_button2.jpg" alt="<?php echo $this->translate('Login with Facebook'); ?>"/></a>
			</p>
			<p class="formlinks"><?php echo $this->translate('Forgotten'); ?> <a href="<?php echo $this->lost_username; ?>"><?php echo $this->translate('Username'); ?></a> | <a href="<?php echo $this->reset_password; ?>"><?php echo $this->translate('Password'); ?></a></p>
		</form>
	</div>
	<div id="sidebar">
		<div class="box">
			<div class="pad">
				<div class="content">
					<h3 class="title"><?php echo $this->translate('Current Stats'); ?></h3>
					<div class="rates">
						<div class="column">
							<h4><?php echo $this->usersCount?></h4>
							<p class="label"><?php echo $this->usersCount; ?> <?php echo $this->usersCount > 1 ? $this->translate('members') : $this->translate('member'); ?></p>
						</div>
						<div class="column border">
							<h4><?php echo $this->itemsCount?></h4>
							<p class="label"><?php echo $this->itemsCount > 1 ? $this->translate('Items') : $this->translate('Item'); ?></p>
						</div>
						<div class="clear"></div>
					</div>
				</div>	
			</div>
		</div>
	</div>
	<div class="clear"></div>
</div>

<?php echo $this->footer_part; ?>