<?php echo $this->header_part; ?>

<div id="content">
	<div class="breadcrumb">
		<p><?php
			$output = array();
			foreach($this->crumbs as $crumb) {
				if(isset($crumb['href']))
					$output[] = '<a href="'. $crumb['href'] .'">'. $crumb['name'] .'</a>';
				else
					$output[] = $crumb['name'];
			}
			
			echo implode(' &nbsp;&rsaquo;&nbsp; ', $output);
		?></p>
	</div>
	<?php echo $this->author_header; ?>
	<div id="main" class="withhead">
		<h3 class="title-5"><?php echo $this->translate('Statement'); ?></h3>
		<table cellpadding="0" cellspacing="0" border="0" class="table-1">
			<tr>
				<th width="25%"><span class="silver"><?php echo ucfirst($this->translate('Date')); ?></span></th>
				<th width="25%"><?php echo $this->translate('Type'); ?></th>
				<th width="25%"><?php echo $this->translate('Amount'); ?></th>
				<th class="right"><?php echo $this->translate('Details'); ?></th>
			</tr>
			<?php if($this->statements) { ?>
			<?php $i = 0; ?>
			<?php foreach($this->statements as $statement) { ?>
			<?php if(isset($statement['total_earnings'])) { ?>
			<tr>
				<td colspan="4"><a href="#" class="expand" rel="expand-id-<?php echo ++$i; ?>"><?php echo $statement['month']; ?></a></td>
			</tr>
			<?php } else { ?>
			<tr class="hide expand-id-<?php echo $i; ?>">
				<td><?php echo $statement['day']; ?></td>
				<td><?php echo $statement['type']; ?></td>
				<td><?php echo $statement['price']; ?></td>
				<td class="right"><?php echo $statement['details']; ?></td>
			</tr>
			<?php } ?>
			<?php } ?>
			<?php } else { ?>
			<tr><td colspan="4"><?php echo $this->translate('No results yet'); ?></td></tr>	
			<?php } ?>
		</table>
	</div>
	<div id="sidebar" class="withhead">
		<div class="box">
			<div class="pad">
				<div class="content">
					<p class="icon"><?php echo $this->translate('You can download your statements in'); ?> <a href="<?php echo $this->csv_link; ?>">CSV <?php echo $this->translate('format'); ?></a>, <?php echo $this->translate('open it in a spreadsheet and perform your own calculations, graphing, etc'); ?>.</p>
				</div>	
			</div>
		</div>
		<div class="box">
			<div class="pad">
				<div class="content">
					<h3 class="title"><?php echo $this->translate('Current Rate'); ?></h3>
					<div class="rates">
						<div class="column">
							<h4><?php echo $this->percent['percent'];?>%</h4>
							<p class="label"><?php echo $this->translate('Rates'); ?></p>
							<p class="tip"><a href="#" class="tooltip" title="<?php echo $this->translate('Your rates are determined based on whether you are selling items exclusively on the Marketplaces and on your volume of sales.'); ?>">?</a></p>
						</div>
						<div class="column border">
							<h4><?php echo (int)$this->total_sales_cnt; ?></h4>
							<p class="label"><?php echo $this->translate('Total Sales'); ?></p>
						</div>
						<div class="clear"></div>
					</div>
					</ul>
				</div>	
			</div>
		</div>
		<div class="balance">
			<h3><?php echo $this->translate('Current balance'); ?></h3>
			<p class="total"><?php echo $this->total_balance; ?></p>
			<p class="button"><a href="<?php echo $this->withdrawal_link; ?>" class="button-blue"><?php echo $this->translate('Request Payout'); ?></a></p>
		</div>
		<div class="box">
			<div class="pad">
				<div class="content">
					<p class="nm"><?php echo $this->translate('Need a tax invoice?'); ?><br /><?php echo $this->translate('Make sure you\'ve added your company name to the'); ?> <a href="<?php echo $this->settings_link; ?>"><?php echo $this->translate('Settings'); ?></a>.</p>
				</div>	
			</div>
		</div>
	</div>
	<div class="clear"></div>
</div>

<?php echo $this->footer_part; ?>