<?php echo $this->header_part; ?>

<div id="content">
	<div class="breadcrumb">
		<p><?php
			$output = array();
			foreach($this->crumbs as $crumb) {
				if(isset($crumb['href']))
					$output[] = '<a href="'. $crumb['href'] .'">'. $crumb['name'] .'</a>';
				else
					$output[] = $crumb['name'];
			}
			
			echo implode(' &nbsp;&rsaquo;&nbsp; ', $output);
		?></p>
	</div>
	<div class="titlehead inner">
		<h2 class="title-3"><?php echo $this->headline; ?></h2>
		<div class="clear"></div>
	</div>
	<div class="stats nomemberbox">
		<?php $cnt = count($this->mainCategories); ?>
		<p><?php for($i = 0; $i < $cnt; $i++) { ?>
			<?php if((isset($this->sel_thread) && $this->sel_thread == $this->mainCategories[$i]['id']) || (!isset($this->sel_thread) && $i == 0)) { ?>
			<a href="<?php echo $this->mainCategories[$i]['href']; ?>" class="active"><?php echo $this->mainCategories[$i]['name']; ?></a> 
			<?php } else { ?>
			<a href="<?php echo $this->mainCategories[$i]['href']; ?>"><?php echo $this->mainCategories[$i]['name']; ?></a> 
			<?php } ?>
			<?php } ?>	
		</p>
		<div class="clear"></div>
	</div>
	<div id="main" class="withhead" style="margin-top:12px;">
		<?php if(isset($this->msg_success)) { ?>
		<p id="msg" class="item_msg box-success mgnt20px"><?php echo $this->msg_success; ?></p>
		<?php } ?>
		<?php if(isset($this->error['msg_error'])) { ?>
		<p id="msg" class="item_msg box-error mgnt20px"><?php echo $this->error['msg_error']; ?></p>
		<?php } ?>
		<?php if($this->pagination) { ?>
		<div class="pagination">
			<p><?php echo $this->pagination; ?></p>
		</div>
		<div class="clear"></div>
		<?php } ?>
		<div class="comments">
			<?php if($this->threads) { ?>
			<ul>
				<?php $i = 0; ?>
				<?php foreach($this->threads as $thread) { ?>
				<li class="cmmnt" id='c_<?php echo $thread['id']; ?>'>
					<p class="avatar ntm">
						<a href="<?php echo $thread['userhref']; ?>"><img src="<?php echo $thread['avatar']; ?>" alt="<?php echo $thread['owner']; ?>" /></a>
						<?php if($thread['lavatar']) { ?>
						<a href="<?php echo $thread['lhref']; ?>" class="small"><img src="<?php echo $thread['lavatar']; ?>" alt="<?php echo $thread['lusername']; ?>" /></a>
						<?php } ?>
						<span><?php echo $thread['usr_posts']?> <?php echo $thread['usr_posts'] == 1 ? $this->translate('Post') : $this->translate('Posts'); ?></span>
						<?php if(!empty($thread['badges'])) { ?>
						<span><?php foreach($thread['badges'] as $badg) { ?>
							<img src="<?php echo $badg['photo']?>" alt="<?php echo $badg['name']?>" title="<?php echo $badg['name']?>" />
							<?php }?></span>
						<?php } ?>
					</p>
					<div class="comment">
						<h4 class="name" style="width: 350px;"><a href="<?php echo $thread['threadhref']; ?>" class="h_forum"><?php echo $thread['name']; ?></a></h4>
						<div class="replys_forum">
							<span class="position"><?php echo $thread['cnt']; ?></span>
							<a href="<?php echo $thread['threadhref']; ?>"><?php echo $thread['cnt'] == 1 ? $this->translate('reply') : $this->translate('replies'); ?></a>
						</div>
						<div class="text" style="width: 350px;">
							<p><a href="<?php echo $thread['threadhref']; ?>"><?php echo $this->translate('started'); ?></a> <?php echo $this->translate('by'); ?> <a href="<?php echo $thread['userhref']; ?>"><?php echo $thread['owner']?></a> - <?php echo $thread['first_date']; ?></p>
							<?php if(!empty($thread['lusername'])) { ?>
							<p><a href="<?php echo $thread['lasthref']; ?>"><?php echo $this->translate('latest reply'); ?></a> <?php echo $this->translate('by'); ?> <a href="<?php echo $thread['lhref']; ?>"><?php echo $thread['lusername']?></a> - <?php echo $thread['last_date']; ?></p>
							<?php } ?>
							<?php if(JO_Session::get('username') && JO_Session::get('username') != $thread['owner']) { ?>
							<ul class="cat rply_btn">
								<li>
									 <a href="<?php echo $thread['reporthref']; ?>"><?php echo $this->translate('Report'); ?></a>
								</li>
							</ul>
							<?php } ?>
						</div>
					</div>
					<div class="clear"></div>
				</li>
				<?php } ?>
			</ul>
			<?php } else { ?>
				<div class="viewall ntp"><p><?php echo $this->translate('No comments for this topic yet'); ?></p></div>
			<?php } ?>
			<div class="clear mgnt20px"></div>
			<?php if($this->pagination) { ?>
			<div class="pagination bottom">
				<p><?php echo $this->pagination; ?></p>
			</div>
			<div class="clear mgnt20px"></div>
			<?php } ?>
			<?php if(JO_Session::get('user_id')) { ?>
			<h2 id="cform"><?php echo $this->translate('Add new thread'); ?></h2>
			<hr />
			<form name="comment_form" method="post" action="<?php echo $this->add_comment_link; ?>" class="form" style="margin-top: 15px;">
				<?php if(!isset($this->sel_thread)) { ?>
				<p class="input">
					<label for="new_topic" class="label"><?php echo $this->translate('Topic'); ?> *<br class="hide" /></label>
					<select name="thread_id" id="new_topic">
						<?php for($i = 1; $i < $cnt; $i++) { ?>
							<option value="<?php echo $this->mainCategories[$i]['id']; ?>"<?php echo (isset($this->data['thread_id']) && $this->data['thread_id'] == $this->mainCategories[$i]['id']) ? ' selected="selected"' : '';?>><?php echo $this->mainCategories[$i]['name']; ?></option>
						<?php } ?>
					</select>
				</p>
				<?php } else {?>
				<p class="hide"><input type="hidden" name="thread_id" value="<?php echo $this->sel_thread;?>"/></p>
				<?php } ?>
				<?php if(isset($this->error['name'])) { ?>
				<p class="small errormessage"><?php echo $this->error['name'];?></p>
				<?php } ?>
				<p class="input">
					<label for="f2" class="label"><?php echo $this->translate('Subject'); ?> *<br class="hide" /></label>
					<input type="text" name="name" id="f2" value="<?php echo isset($this->data['name']) ? $this->data['name'] : ''; ?>" <?php echo isset($this->error['name']) ? 'class="errorborder" ' : '' ;?>/>
				</p>
				<?php if(isset($this->error['comment'])) { ?>
				<p class="small errormessage"><?php echo $this->error['comment'];?></p>
				<?php } ?>
				<div class="textarea">
					<label for="comment" class="label" style="height:50px;"><?php echo $this->translate('Comment'); ?> *<br class="hide" /></label>
					<textarea name="comment" id="comment" rows="10"></textarea>
					<?php if(!empty($this->smiles)) { ?>
					<div class="clear"></div>
					<p class="small"><?php echo $this->smiles; ?></p>
					<div class="clear"></div>
					<? } ?>
				</div>
				<div class="check">
					<p class="label"></p>
					<div class="pack">
						<p>
							<input type="checkbox" name="reply_notification" value="1" id="reply_notification" /><label for="reply_notification"><?php echo $this->translate('Notify me when I recieve a reply');?></label>
						</p>
					</div>
					<div class="clear"></div>
				</div>
				<p class="submit"><input type="submit" value="<?php echo $this->translate('Add Comment'); ?>" /></p>
			</form>
			<?php } ?>
		</div>
	</div>
	<?php echo $this->rightside; ?>
	<div class="clear"></div>	
</div>

<?php echo $this->footer_part; ?>