<?php 
	$module = $this->getRequest()->getModule();
?>

<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/<?php echo $module;?>/images/extensions.png">
		<?php echo $this->translate('Top banner');?>
	</h3>
	
	<?php if($this->successfu_edite) { ?>
	<span id="fader" class="fleft mleft30"><span class="msgOk"><span><?php echo $this->translate('Successfully!');?></span><?php echo $this->translate('Information was successfully changed!');?></span></span>
	<script type="text/javascript"> 
	// <![CDATA[
	$(document).ready(function() {       
		setTimeout(function() {
			$("#fader").customFadeOut("slow" ,    
			function() {       
				$("#fader").remove();  
			});
		},
		4000);
	});
	// ]]>
	</script>
	<?php } ?>
	
	<div class="fright mtop3">
		<a class="button" href="<?php echo $module;?>/extensions/"><?php echo $this->translate('Back');?></a>
		<a class="button" href="<?php echo $module;?>/extensions/edit/?extension=topbanner&call=create&page=<?php echo $this->page_num;?>"><?php echo $this->translate('Add new');?></a>
	</div>
	<div class="clear"></div>
</div>



<p class="info">
	<?php echo $this->translate('Top banner Manager');?>.<br>
</p>

<table cellspacing="0" cellpadding="0" class="display">
	<thead>
		<tr class="nodrop nodrag">
			<th class="left"><?php echo $this->translate('Name');?></th>
			<th class="left"><?php echo $this->translate('Url');?></th>
			<th class="left"><?php echo $this->translate('From');?></th>
			<th class="left"><?php echo $this->translate('To');?></th>
			<th class="left"><?php echo $this->translate('Views');?></th>
			<th class="left"><?php echo $this->translate('Clicks');?></th>
			<th class="left"><?php echo $this->translate('Close option enabled');?></th>
			<th width="50"><?php echo $this->translate('Edit');?></th>
			<th width="50"><?php echo $this->translate('Delete');?></th>
		</tr>
	</thead>
	<tbody>
	<?php if($this->banners) { ?>
	<?php foreach($this->banners AS $banner) { ?>
		<tr id="<?php echo $banner['id'];?>">
			<td><?php echo $banner['name'];?></td>
			<td><?php echo $banner['url'];?></td>
			<td><?php echo $banner['from'];?></td>
			<td><?php echo $banner['to'];?></td>
			<td><?php echo $banner['views'];?></td>
			<td><?php echo $banner['clicks'];?></td>
			<td>
				<a href="javascript:void(0);" onclick="changeStatus(<?php echo $banner['id'];?>);">
					<img src="cms/<?php echo $module;?>/images/<?php echo ($banner['close'] == 'true' ? 'yes.png' : 'no.png');?>" class="tooltip"  alt="" title="<?php echo ($banner['close'] == 'true' ? $this->translate('Yes') : $this->translate('No'));?>" />
				</a>
			</td>
            
			<td align="center">
				<a href="<?php echo $module;?>/extensions/edit/?extension=topbanner&call=edit&page=<?php echo $this->page_num;?>&id=<?php echo $banner['id'];?>">
					<img title="<?php echo $this->translate('Edit');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/edit.png">
				</a>
			</td>
			<td align="center">
				<a id="item_<?php echo $banner['id'];?>" class="delete" href="javascript:void(0);">
					<img title="<?php echo $this->translate('Delete');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/delete.png">
				</a>
			</td>
			
		</tr>
	<?php } ?>
	<?php } else { ?>
		<tr class="nodrop nodrag">
			<td colspan="9">
				<div class="msgAlert"><span><?php echo $this->translate('Attention!');?></span><?php echo $this->translate('No records found ...');?></div>
			</td>
		</tr>
	<?php } ?>
	</tbody>
</table>

<?php if($this->pagination) { ?>
<br />
<div class="fleft">
<?php echo $this->translate('Page');?> <b><?php echo $this->page_num;?></b> <?php echo $this->translate('from');?> <b><?php echo $this->total_pages;?></b> (<b><?php echo $this->total_rows;?></b> <?php echo $this->translate('records');?>)
</div>
<div class="pagination fright">
	<?php echo $this->pagination;?>
</div>
<div class="clear"></div>
<?php } ?>

<script type="text/javascript"> 
// <![CDATA[

changeStatus = function(id) {
	$.ajax({
        type: 'post',
        url: "<?php echo $module;?>/extensions/edit/?extension=topbanner&call=changeStatus",
        data: 'id=' + id,
        beforeSend: function () {
			$('#'+id).animate({
                'backgroundColor': '#FFBFBF'
            }, 400);
        },
        success: function () {
        	$.get(window.location.href, function(data){
        		$('#'+id).html($(data).find('#'+id).html());
        		setTimeout(function(){
        			$("#"+id+"").animate({'backgroundColor': 'transparent'}, 400).find('.tooltip').simpletooltip();
        			deleteInit();
        		}, 500);
        	});
        }
	});
};

$(document).ready(function(){
	deleteInit();
});

function deleteInit() {
	$('a.delete').click(function (e) {
        if (confirm(lang.confirm)) {
            e.preventDefault();
            var parent = $(this).parents('tr');
            $.ajax({
                type: 'post',
                url: "<?php echo $module;?>/extensions/edit/?extension=topbanner&call=delete",
                data: 'id=' + $(this).attr('id').replace('item_', ''),
                beforeSend: function () {
                    parent.animate({
                        'backgroundColor': '#FFBFBF'
                    }, 400);
                },
                success: function () {
                    parent.fadeOut(400, function () {
                        parent.remove();
                    });
                }
            });
        }
    });
}
// ]]>
</script>