<?php 
	$module = $this->getRequest()->getModule();
?>

<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/<?php echo $module;?>/images/percents.png">
		<?php echo $this->translate('Deposits Management');?>
	</h3>
	
	<?php if($this->successfu_edite) { ?>
	<span id="fader" class="fleft mleft30"><span class="msgOk"><span><?php echo $this->translate('Successfully!');?></span><?php echo $this->translate('Information was successfully changed!');?></span></span>
	<script type="text/javascript"> 
	// <![CDATA[
	$(document).ready(function() {       
		setTimeout(function() {
			$("#fader").customFadeOut("slow" ,    
			function() {       
				$("#fader").remove();  
			});
		},
		4000);
	});
	// ]]>
	</script>
	<?php } ?>
	
	<div class="fright mtop3">
		<a class="button" href="<?php echo $module;?>/deposits/create/"><?php echo $this->translate('Add new record');?></a>
	</div>
	<div class="clear"></div>
</div>


<p class="info">
	<?php echo $this->translate('Deposits Management');?><br>
	<strong><?php echo $this->translate('Note: If you delete an entry, information will be lost.');?></strong>
</p>


<table cellspacing="0" cellpadding="0" class="display">
	<thead>
		<tr class="nodrop nodrag">
			<th class="left"><?php echo $this->translate('Deposit');?></th>
			<th width="50"><?php echo $this->translate('Edit');?></th>
			<th width="50"><?php echo $this->translate('Delete');?></th>
		</tr>
	</thead>
	<tbody>
	<?php if($this->percents) { ?>
	<?php foreach($this->percents AS $percent) { ?>
		<tr>
			<td><?php echo $percent['deposit'];?></td>
			<td align="center"><a href="<?php echo $module;?>/deposits/edit/?id=<?php echo $percent['id'];?>"><img title="<?php echo $this->translate('Edit');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/edit.png"></a></td>
			<td align="center"><a id="item_<?php echo $percent['id'];?>" class="delete" href="javascript:void(0);"><img title="<?php echo $this->translate('Delete');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/delete.png"></a></td>
		</tr>
	<?php } ?>
	<?php } else { ?>
		<tr class="nodrop nodrag">
			<td colspan="5">
				<div class="msgAlert"><span><?php echo $this->translate('Attention!');?></span><?php echo $this->translate('No records found ...');?></div>
			</td>
		</tr>
	<?php } ?>
	</tbody>
</table>

<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function(){
	$('a.delete').click(function (e) {
        if (confirm(lang.confirm)) {
            e.preventDefault();
            var parent = $(this).parents('tr');
            $.ajax({
                type: 'post',
                url: "<?php echo $module;?>/deposits/delete",
                data: 'id=' + $(this).attr('id').replace('item_', ''),
                beforeSend: function () {
                    parent.animate({
                        'backgroundColor': '#FFBFBF'
                    }, 400);
                },
                success: function () {
                    parent.fadeOut(400, function () {
                        parent.remove();
                    });
                }
            });
        }
    });
});

// ]]>
</script>