<?php 
	$module = $this->getRequest()->getModule();
?>
<script type="text/javascript">
	$(function() {
		$('.lg').click(function() {
			var id = $(this).attr('rel');
			$(this).addClass('selected').parent().siblings().find('a').removeClass('selected');
			$('#descr_' + id).show().siblings('input').hide();
			$('#descr_' + id).next('img').show().siblings('img').hide();
			return false;
		});
	});
</script>
<form name="admin_form" id="admin_form" method="post" action="" enctype="multipart/form-data">
	<div class="info_line top">
		<h3 class="fleft title">
			<img alt="" src="cms/<?php echo $module;?>/images/percents.png">
			<?php echo $this->translate('Membership Management');?>
		</h3>
		<span id="fader" class="fleft mleft30" style="display:none;">
			<span class="msgError"><span><?php echo $this->translate('Error!');?></span><i class="error_text"></i></span>
		</span>
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/membership/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
	<div class="tabs mtop10">
		<ul>
			<?php foreach($this->languages AS $language) { ?>
			<li>
				<a href="#" rel="<?php echo $language['language_id'];?>" class="<?php echo $this->def_lang == $language['code'] ? 'selected ' : '';?>lg">
					<img src="cms/images/flags/<?php echo $language['image'];?>" />
					<?php echo $language['name'];?>
				</a>
			</li> 
			<?php } ?>
		</ul>
		<div class="clear"></div>
	</div>
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Status');?>: </td>
				<td>
					<select name="status">
						<?php if($this->status == 'true') { ?>
						<option selected="selected" value="true"><?php echo $this->translate('Enabled');?></option>
						<option value="false"><?php echo $this->translate('Disabled');?></option>
						<?php } else { ?>
						<option value="true"><?php echo $this->translate('Enabled');?></option>
						<option selected="selected" value="false"><?php echo $this->translate('Disabled');?></option>
						<?php } ?>
					</select>
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Price');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" title="<?php echo $this->translate('Please enter price');?>" size="15" value="<?php echo $this->price;?>" class="inputbox required"  name="price" />
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Number of products for download');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" title="<?php echo $this->translate('Please enter number of products');?>" size="15" value="<?php echo $this->max_items_cnt;?>" class="inputbox required"  name="max_items_cnt" />
					&nbsp;&nbsp; <img title="<?php echo $this->translate('For unlimited downloads leave 0');?>" class="tooltip" alt="Tip" src="cms/<?php echo $module;?>/images/sinfo.gif">
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Position');?>: </td>
				<td>
					<input type="text" title="<?php echo $this->translate('Please enter position number');?>" size="15" value="<?php echo $this->order_index;?>" class="inputbox"  name="order_index" />
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Description');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<?php foreach($this->languages AS $language) { ?>
					<input type="text" size="40" id="descr_<?php echo $language['language_id'];?>" name="description[<?php echo $language['language_id']; ?>]" value="<?php echo $this->description[$language['language_id']]; ?>"  class="inputbox"<?php echo ($language['code'] != $this->def_lang) ? ' style="display:none; "' : '';?>/>
					<img src="cms/images/flags/<?php echo $language['image'];?>"<?php echo ($language['code'] != $this->def_lang) ? ' style="display:none; "' : '';?>/>
					<?php } ?>
				</td>
			</tr>
		</tbody>
	</table>
	<div class="info_line bottom">
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/membership/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>	
</form>