<?php echo $this->header_part; ?>


<div id="content">
	<div class="breadcrumb">
		<p><?php
			$output = array();
			foreach($this->crumbs as $crumb) {
				if(isset($crumb['href']))
					$output[] = '<a href="'. $crumb['href'] .'">'. $crumb['name'] .'</a>';
				else
					$output[] = $crumb['name'];
			}
			
			echo implode(' &nbsp;&rsaquo;&nbsp; ', $output);
		?></p>
	</div>
	<div class="titlehead inner">
		<h2 class="title-3"><?php echo $this->item['name']; ?></h2>
		<div class="clear"></div>
	</div>
	<div class="stats nomemberbox">
		<p><a href="<?php echo $this->item_link; ?>"><?php echo $this->translate('Item Details'); ?></a> 
			<?php if($this->faq_link) { ?>
			<a href="<?php echo $this->faq_link; ?>" class="active"><?php echo $this->translate('Faq'); ?></a> 
			<?php } ?>
			<a href="<?php echo $this->comment_link; ?>"><?php echo $this->translate('Comments'); ?></a> 
			<?php if($this->edit_link) { ?>
			<a href="<?php echo $this->edit_link; ?>"><?php echo $this->translate('Edit'); ?></a> 
			<?php } ?>
			<?php if($this->delete_link) { ?>
				<a href="#" onclick="javascript: if(confirm('<?php echo $this->translate('Are you sure you want to delete the item? Once deleted it can not ne restored again!'); ?>')){ window.location.href='<?php echo $this->delete_link; ?>';} return false;"><?php echo $this->translate('Delete'); ?></a>
			<?php } ?>
		</p>
		<div class="clear"></div>
	</div>
	<div id="main" class="withhead">
		<?php if(isset($this->msg_success)) { ?>
		<p id="msg" class="item_msg box-success"><?php echo $this->msg_success; ?></p>
		<?php } ?>
		<?php if(isset($this->msg_error)) { ?>
		<p id="msg" class="item_msg box-error"><?php echo $this->msg_error; ?></p>
		<?php } ?>
		<div class="textbox textpage">
			<h2 class="ntp"><?php echo $this->translate('Frequently Asked Questions'); ?></h2>
			<?php if($this->faq) { ?>
			<dl>
				<?php $i = 0; ?>
				<?php foreach($this->faq as $faq) { ?>
				<dt><span><?php echo $this->translate('Q'); ?>:</span><strong><?php echo $faq['question']; ?></strong></dt>
				<dd><span><?php echo $this->translate('A'); ?>:</span><?php echo $faq['answer']; ?>
					<?php if(JO_Session::get('user_id') == $this->item['user_id']) { ?>
					<ul class="cat">
						<li class="cmmnt_btns"><a href="#" class="rply"><?php echo $this->translate('Edit'); ?></a>
							<div class="dropdown">
								<form action="<?php echo $faq['update']; ?>" method="post" class="form" style="width: 335px;">
									<div class="textarea">
										<textarea name="question" rows="5"><?php echo $faq['question']; ?></textarea>
									</div>
									<div class="clear"></div>
									<div class="textarea">
										<textarea name="answer" class="faq_reply" id="faq_<?php echo $i++; ?>" rows="10"><?php echo $faq['answer']; ?></textarea>
									</div>
									<div class="clear mgnt20px"></div>
									<p><input type="submit" name="submit" value="<?php echo $this->translate('Edit'); ?>" class="button-blue" /></p>
								</form>
							</div>
							<div class="clear"></div>
						</li>
						<li><a href="<?php echo $faq['delete']?>"><?php echo $this->translate('Delete'); ?></a></li>
					</ul>
					<div class="clear"></div>
					<?php } ?>
				</dd>
				<?php } ?>
			</dl>
			<?php } ?>
			<?php if(JO_Session::get('user_id') && JO_Session::get('user_id') == $this->item['user_id']) { ?>
			<div class="clear mgnt20px"></div>
			<hr />
			<form name="faq_form" method="post" action="<?php echo $this->add_faq_link; ?>" class="form" style="margin-top: 15px;">
				<div class="textarea">
					<label for="question" class="label" style="height:50px;"><?php echo $this->translate('Question'); ?> *<br class="hide" /></label>
					<textarea name="question" id="question" rows="5"></textarea>
				</div>
				<div class="clear"></div>
				<div class="textarea">
					<label for="answer_editor" class="label" style="height:50px;"><?php echo $this->translate('Answer'); ?> *<br class="hide" /></label>
					<textarea name="answer" id="answer_editor" rows="10"></textarea>
				</div>
				<div class="clear"></div>
				<p class="submit"><input type="submit" value="<?php echo $this->translate('Create FAQ'); ?>" /></p>
			</form>
			<?php } ?>
		</div>
	</div>
	<?php echo $this->rightside; ?>
	<div class="clear"></div>	
</div>


<?php echo $this->footer_part; ?>