<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<base href="<?php echo $this->getRequest()->getBaseUrl();?>" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title><?php echo $this->item['name']; ?></title>
    <link href="data/themes/favicon.ico" rel="shortcut icon"/>
    <link href="data/themes/css/previewer.css" rel="stylesheet" type="text/css" />
    
</head>
<body>
<div class="comments">
  <div class="fullsize">
    <img src="<?php echo $this->previewFile; ?>" alt="<?php echo $this->item['name'];?>" />
  </div>
  
  <div class="description">
    <h1><?php echo $this->translate('Photo'); ?>  <?php echo (int)$this->getRequest()->getRequest('index')+1; ?></h1>
  </div>
</div>
</body>
</html>
